/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contents;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ICT_7
 */
public class AddAccount extends javax.swing.JFrame {

    int f = 2;
    int a = 0;
    String user = "";
    String pass = "";

    /**
     * Creates new form AddAccount
     */
    public AddAccount() {
        initComponents();
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        txtUser.setBackground(new java.awt.Color(0, 0, 0, 1));
        pwdPass.setBackground(new java.awt.Color(0, 0, 0, 1));
        lblAdmin.setFocusable(false);
        lblUser.setFocusable(false);
        txtUser.setFocusable(false);
        pwdPass.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOne = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlTwo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        pwdPass = new javax.swing.JPasswordField();
        lblAdmin = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblU = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(370, 260));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlOne.setBackground(new java.awt.Color(36, 56, 50));
        pnlOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cross-button.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        pnlOne.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 4, -1, -1));

        lblBack.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setText("Back");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        pnlOne.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(pnlOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 90));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        pnlTwo.setBackground(new java.awt.Color(249, 234, 208));
        pnlTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 56, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(249, 234, 208));
        btnAdd.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(36, 56, 60));
        btnAdd.setText("Add Account");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 150, 40));

        txtUser.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtUser.setForeground(java.awt.Color.gray);
        txtUser.setText("Enter Username");
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtUser.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtUserCaretUpdate(evt);
            }
        });
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 330, 30));

        pwdPass.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        pwdPass.setForeground(java.awt.Color.gray);
        pwdPass.setText("Enter Password");
        pwdPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        pwdPass.setEchoChar((char) 0);
        pwdPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pwdPassCaretUpdate(evt);
            }
        });
        pwdPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdPassFocusLost(evt);
            }
        });
        pwdPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdPassMouseClicked(evt);
            }
        });
        pwdPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdPassKeyPressed(evt);
            }
        });
        jPanel1.add(pwdPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 330, 30));

        lblAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/admin_1.png"))); // NOI18N
        lblAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblAdminFocusGained(evt);
            }
        });
        lblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminMouseClicked(evt);
            }
        });
        jPanel1.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 17, -1, -1));

        lblA.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblA.setForeground(new java.awt.Color(255, 255, 255));
        lblA.setText("Admin");
        jPanel1.add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        lblU.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblU.setForeground(new java.awt.Color(255, 255, 255));
        lblU.setText("User");
        jPanel1.add(lblU, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/user_1.png"))); // NOI18N
        lblUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblUserFocusGained(evt);
            }
        });
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 17, -1, -1));

        pnlTwo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 430, 220));

        getContentPane().add(pnlTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 430, 260));

        setSize(new java.awt.Dimension(430, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-red.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        adder();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        Color customColor = new Color(249, 234, 208);
        txtUser.setText("");
        txtUser.setText(user);
        txtUser.setForeground(customColor);
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        txtUser.setForeground(Color.GRAY);
        if (user.trim().length() != 0 && !user.equals("Enter Username")) {// may trim dito kanina
            txtUser.setText(user);
        } else {
            txtUser.setText("Enter Username");
            user = "";
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void pwdPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPassFocusGained
        Color customColor = new Color(249, 234, 208);
        pwdPass.setText("");
        pwdPass.setText(pass);
        pwdPass.setForeground(customColor);
        pwdPass.setEchoChar('\u25cf');
    }//GEN-LAST:event_pwdPassFocusGained

    private void pwdPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPassFocusLost
        pwdPass.setForeground(Color.GRAY);
        if (pass.trim().length() != 0 && !pass.trim().equals("Enter Password")) {
            txtUser.setText(user);
            pwdPass.setEchoChar('\u25cf');
        } else {
            pwdPass.setText("Enter Password");
            pwdPass.setEchoChar((char) 0);
            pass = "";
        }
    }//GEN-LAST:event_pwdPassFocusLost

    private void txtUserCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtUserCaretUpdate
        user = txtUser.getText();
    }//GEN-LAST:event_txtUserCaretUpdate

    private void pwdPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pwdPassCaretUpdate
        pass = pwdPass.getText();
    }//GEN-LAST:event_pwdPassCaretUpdate

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        txtUser.setFocusable(true);
        pwdPass.setFocusable(true);
        txtUser.requestFocus();
    }//GEN-LAST:event_txtUserMouseClicked

    private void pwdPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdPassMouseClicked
        txtUser.setFocusable(true);
        pwdPass.setFocusable(true);
        pwdPass.requestFocus();
    }//GEN-LAST:event_pwdPassMouseClicked

    private void lblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseClicked
        lblAdmin.requestFocus();
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/user_1.png"));
        lblUser.setIcon(imgIcon);
        check(1);
    }//GEN-LAST:event_lblAdminMouseClicked

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        lblUser.requestFocus();
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/admin_1.png"));
        lblAdmin.setIcon(imgIcon);
        check(0);
    }//GEN-LAST:event_lblUserMouseClicked

    private void lblUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblUserFocusGained
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/user_2.png"));
        lblUser.setIcon(imgIcon);
    }//GEN-LAST:event_lblUserFocusGained

    private void lblAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblAdminFocusGained
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/admin_2.png"));
        lblAdmin.setIcon(imgIcon);
    }//GEN-LAST:event_lblAdminFocusGained

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        new MainFrameAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            adder();
        }
    }//GEN-LAST:event_txtUserKeyPressed

    private void pwdPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            adder();
        }
    }//GEN-LAST:event_pwdPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblU;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlOne;
    private javax.swing.JPanel pnlTwo;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    public void adder() {
        int a = new Methods().checker(txtUser.getText(), pwdPass.getText(), f);
        if (a == 1) {
            new Methods().adder(txtUser.getText(), pwdPass.getText(), f);
            Icon imgIcon = new ImageIcon(getClass().getResource("/icons/user_1.png"));
            lblUser.setIcon(imgIcon);
            Icon imgIcon2 = new ImageIcon(getClass().getResource("/icons/admin_1.png"));
            lblAdmin.setIcon(imgIcon2);
            txtUser.setText("Enter Username");
            pwdPass.setText("Enter Password");
            pass = "";
            pwdPass.setEchoChar((char) 0);
            txtUser.setFocusable(false);
            pwdPass.setFocusable(false);
            a = 0;
        } else {
            Icon imgIcon = new ImageIcon(getClass().getResource("/icons/user_1.png"));
            lblUser.setIcon(imgIcon);
            Icon imgIcon2 = new ImageIcon(getClass().getResource("/icons/admin_1.png"));
            lblAdmin.setIcon(imgIcon2);
        }
        f = -1;
    }

    public void check(int c) {
        if (c == 1) {
            if (a == 0) {
                a = 1;
                Icon imgIcon = new ImageIcon(getClass().getResource("/icons/admin_2.png"));
                lblAdmin.setIcon(imgIcon);
                f = 1;
                System.out.println(f);
            } else if (a == 1) {
                Icon imgIcon = new ImageIcon(getClass().getResource("/icons/admin_1.png"));
                lblAdmin.setIcon(imgIcon);
                a = 0;
                f = -1;
            }
        } else if (c == 0) {
            if (a == 0) {
                a = 1;
                Icon imgIcon = new ImageIcon(getClass().getResource("/icons/user_2.png"));
                lblUser.setIcon(imgIcon);
                f = 0;
                System.out.println(f);
            } else if (a == 1) {
                Icon imgIcon = new ImageIcon(getClass().getResource("/icons/user_1.png"));
                lblUser.setIcon(imgIcon);
                a = 0;
                f = -1;
            }
        }
    }
}
