/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Contents;
//Kung Babaguhin Yung Design Pabago Nalang Ahahahaha

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kurtt
 */
public class ChangeUsername extends javax.swing.JFrame {

    int flag;
    Connection con;
    String newPass = "";
    String confirmNewPass;
    String username = "";
    String password = "";
    String oldUser = "", newUser = "";

    /**
     * Creates new form MainFrame
     */
    public ChangeUsername() {
        initComponents();
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        txtOU.setFocusable(false);
        txtNU.setFocusable(false);
        txtOU.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtNU.setBackground(new java.awt.Color(0, 0, 0, 1));
        lblH_1.setVisible(false);
        lblH_2.setVisible(false);
        lblS_1.setVisible(false);
        lblS_2.setVisible(false);
        sqlconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCU = new javax.swing.JButton();
        txtNU = new javax.swing.JTextField();
        txtOU = new javax.swing.JTextField();
        lblS_1 = new javax.swing.JLabel();
        lblH_1 = new javax.swing.JLabel();
        lblS_2 = new javax.swing.JLabel();
        lblH_2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 56, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cPassTop_new.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cross-button.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        jPanel3.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 0, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 80));

        jPanel2.setBackground(new java.awt.Color(249, 234, 208));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCU.setBackground(new java.awt.Color(249, 234, 208));
        btnCU.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnCU.setForeground(new java.awt.Color(36, 56, 60));
        btnCU.setText("Change Username");
        btnCU.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCU.setFocusable(false);
        btnCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUActionPerformed(evt);
            }
        });
        jPanel2.add(btnCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 190, 40));

        txtNU.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtNU.setForeground(java.awt.Color.gray);
        txtNU.setText("Enter New Username");
        txtNU.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNU.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNUCaretUpdate(evt);
            }
        });
        txtNU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNUFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNUFocusLost(evt);
            }
        });
        txtNU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNUMouseClicked(evt);
            }
        });
        jPanel2.add(txtNU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 75, 310, 25));

        txtOU.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtOU.setForeground(java.awt.Color.gray);
        txtOU.setText("Enter Old Username");
        txtOU.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtOU.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtOUCaretUpdate(evt);
            }
        });
        txtOU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOUFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOUFocusLost(evt);
            }
        });
        txtOU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOUMouseClicked(evt);
            }
        });
        jPanel2.add(txtOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, 310, 25));

        lblS_1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblS_1.setForeground(java.awt.Color.gray);
        lblS_1.setText("SHOW");
        lblS_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblS_1MouseClicked(evt);
            }
        });
        jPanel2.add(lblS_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 42, -1, -1));

        lblH_1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblH_1.setForeground(java.awt.Color.gray);
        lblH_1.setText("HIDE");
        lblH_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblH_1MouseClicked(evt);
            }
        });
        jPanel2.add(lblH_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 42, -1, -1));

        lblS_2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblS_2.setForeground(java.awt.Color.gray);
        lblS_2.setText("SHOW");
        lblS_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblS_2MouseClicked(evt);
            }
        });
        jPanel2.add(lblS_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 82, -1, -1));

        lblH_2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblH_2.setForeground(java.awt.Color.gray);
        lblH_2.setText("HIDE");
        lblH_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblH_2MouseClicked(evt);
            }
        });
        jPanel2.add(lblH_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 82, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/bottompart_2.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 370, 180));

        setSize(new java.awt.Dimension(370, 260));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-red.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUActionPerformed
        changeUsername();
    }//GEN-LAST:event_btnCUActionPerformed

    private void lblS_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblS_1MouseClicked
//        showPassword1();
//        lblS_1.setVisible(false);
    }//GEN-LAST:event_lblS_1MouseClicked

    private void lblS_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblS_2MouseClicked
//        showPassword2();
//        lblS_2.setVisible(false);
    }//GEN-LAST:event_lblS_2MouseClicked

    private void lblH_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblH_1MouseClicked
//        hidePassword1();
    }//GEN-LAST:event_lblH_1MouseClicked

    private void lblH_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblH_2MouseClicked
//        hidePassword2();
    }//GEN-LAST:event_lblH_2MouseClicked

    private void txtNUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNUFocusGained
        Color customColor = new Color(249, 234, 208);
        txtNU.setText("");
        txtNU.setText(newUser);
        txtNU.setForeground(customColor);
    }//GEN-LAST:event_txtNUFocusGained

    private void txtNUFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNUFocusLost
        txtNU.setForeground(Color.GRAY);
        if (newUser.trim().length() != 0 && !newUser.equals("Enter New Username")) {// may trim dito kanina
            txtNU.setText(newUser);
        } else {
            txtNU.setText("Enter New Username");
            newUser = "";
        }
    }//GEN-LAST:event_txtNUFocusLost

    private void txtOUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOUFocusGained
        Color customColor = new Color(249, 234, 208);
        txtOU.setText("");
        txtOU.setText(oldUser);
        txtOU.setForeground(customColor);
    }//GEN-LAST:event_txtOUFocusGained

    private void txtOUFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOUFocusLost
        txtOU.setForeground(Color.GRAY);
        if (oldUser.trim().length() != 0 && !oldUser.equals("Enter Old Username")) {// may trim dito kanina
            txtOU.setText(oldUser);
        } else {
            txtOU.setText("Enter Old Username");
            oldUser = "";
        }
    }//GEN-LAST:event_txtOUFocusLost

    private void txtOUCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtOUCaretUpdate
        oldUser = txtOU.getText();
    }//GEN-LAST:event_txtOUCaretUpdate

    private void txtNUCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNUCaretUpdate
        newUser = txtNU.getText();
    }//GEN-LAST:event_txtNUCaretUpdate

    private void txtNUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNUMouseClicked
        txtOU.setFocusable(true);
        txtNU.setFocusable(true);
        txtNU.requestFocus();
    }//GEN-LAST:event_txtNUMouseClicked

    private void txtOUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOUMouseClicked
        txtOU.setFocusable(true);
        txtNU.setFocusable(true);
        txtOU.requestFocus();
    }//GEN-LAST:event_txtOUMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeUsername().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCU;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblH_1;
    private javax.swing.JLabel lblH_2;
    private javax.swing.JLabel lblS_1;
    private javax.swing.JLabel lblS_2;
    private javax.swing.JTextField txtNU;
    private javax.swing.JTextField txtOU;
    // End of variables declaration//GEN-END:variables

    public void sqlconnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql:///dbAccount", "root", "");

        } catch (Exception e) {
            System.out.println("Connection Error: " + e);
        }
    }

    public void UpdateUsername() {
        try {

            String sql = "update infologin set username = ? where username = ?";
            String sqll = "update infouser set username = ? where username = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            PreparedStatement pstt = con.prepareStatement(sqll);
            LogIn li = new LogIn();
            pst.setString(1, newUser);
            pst.setString(2, txtOU.getText());
            pstt.setString(1, newUser);
            pstt.setString(2, txtOU.getText());
            pst.executeUpdate();
            pstt.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Username Changed!");
            audit(newUser,txtOU.getText(),0);
            MainFrameUser mfu = new MainFrameUser();
            mfu.setPassword(password);
            mfu.getUsername(newUser);
            mfu.setVisible(true);
            dispose();

        } catch (Exception e) {
            System.out.println("Error in UpdateStatus1: " + e);
        }
    }

    public void changeUsername() {
        int x = 0;
        int c = check();
        if (c == 1) {
            try {
                Statement st = con.createStatement();
                String sql = "select * from infologin";
                ResultSet rs = st.executeQuery(sql);

                while (rs.next()) {
                    if (rs.getString("username").equals(txtOU.getText())) {
                            UpdateUsername();
                            x = 0;
                            break;
                    }else{
                    x = 1;
                    }
                }
            } catch (Exception e) {
                System.out.println("Error in changeUsername: " + e);
            }
        }
        if(x == 1){
                    JOptionPane.showMessageDialog(rootPane, "Old Username Does Not Match!");
                    }
    }

    public int check() {
        String ou = txtOU.getText();
        String nu = txtNU.getText();
        int c = 0;
        if (ou.trim().length() != 0 && !ou.equals("Enter Old Username")) {

            if (nu.trim().length() != 0 && !nu.equals("Enter New Username")) {
                if (ou.equals(nu)) {
                    JOptionPane.showMessageDialog(rootPane, "Old username and new username must not be the same!");
                } else {
                    c = 1;
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "New username must not be blank!");
                ou = "";
                nu = "";
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Old username must not be blank!");
            ou = "";
        }
        return c;
    }
    public void showPassword1() {
//        System.out.println(flag);
//        if (flag == 0) {
////                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/1667188461554126440-128.png"));
////                lblEye.setIcon(ImgIcon);
//            pwdCP.setEchoChar((char) 0);
////            lblS_1.setText("HIDE");
//            lblH_1.setVisible(true);
//            flag = 1;
//        }
//        else if (flag == 1) {
//
//            pwdCP.setEchoChar('\u25cf');
//            lblS_1.setVisible(true);
////            lblS_1.setb
//            flag = 0;
//        }
    }

    public void showPassword2() {
//        if (flag == 0) {
////                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/1667188461554126440-128.png"));
////                lblEye.setIcon(ImgIcon);
//            pwdCCP.setEchoChar((char) 0);
//            lblH_2.setVisible(true);
//            flag = 1;
//        }
//        else if (flag == 1) {
////                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/19318253741554126440-128.png"));
////                lblEye.setIcon(ImgIcon);
//            pwdCCP.setEchoChar('\u25cf');
//            lblS_2.setText("SHOW");
//            flag = 0;
//        }
    }

    public void hidePassword1() {
//        pwdCP.setEchoChar('\u25cf');
//        lblS_1.setVisible(true);
//        lblH_1.setVisible(false);
////            lblS_1.setb
//        flag = 0;
    }

    public void hidePassword2() {
//        pwdCCP.setEchoChar('\u25cf');
//        lblS_2.setVisible(true);
//        lblH_2.setVisible(false);
//        flag = 0;
    }

    public void setUsername(String x) {
        username = x;
    }

    public String getUsername() {
        return username;
    }
    
    public void setPassword (String y) {
        password = y;
    }

    public void audit(String username_new, String username_old, int i) {
        String format = "yyyy-MM-dd hh:mm:ss";
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat(format);
        System.out.println(sdf.format(date));
        String sql = "insert into audit values(?,?,?,?)";

        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, sdf.format(date));
            pst.setString(2, username_new);
            pst.setInt(3, i);
            pst.setString(4, "Changed Username: ("+username_old+")");
            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
}
