/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Contents;
//Kung Babaguhin Yung Design Pabago Nalang Ahahahaha

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kurtt
 */
public class ChangePasswordUser extends javax.swing.JFrame {

    int flag;
    Connection con;
    String currentPass = "";
    String newPass = "";
    String confirmNewPass;
    String username = "";
    String password = "";

    /**
     * Creates new form MainFrame
     */
    public ChangePasswordUser() {
        initComponents();
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        pwdCP.setFocusable(false);
        pwdCCP.setFocusable(false);
        pwdOP.setFocusable(false);
        pwdOP.setBackground(new java.awt.Color(0, 0, 0, 1));
        pwdCP.setBackground(new java.awt.Color(0, 0, 0, 1));
        pwdCCP.setBackground(new java.awt.Color(0, 0, 0, 1));
        lblH_1.setVisible(false);
        lblH_2.setVisible(false);
        lblS_1.setVisible(false);
        lblS_2.setVisible(false);
        sqlconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCP = new javax.swing.JButton();
        pwdCCP = new javax.swing.JPasswordField();
        pwdCP = new javax.swing.JPasswordField();
        pwdOP = new javax.swing.JPasswordField();
        lblS_1 = new javax.swing.JLabel();
        lblH_1 = new javax.swing.JLabel();
        lblS_2 = new javax.swing.JLabel();
        lblH_2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBack.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/back_new.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, -1, -1));

        jPanel2.setBackground(new java.awt.Color(249, 234, 208));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCP.setBackground(new java.awt.Color(249, 234, 208));
        btnCP.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnCP.setForeground(new java.awt.Color(36, 56, 60));
        btnCP.setText("Change Password");
        btnCP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCP.setFocusable(false);
        btnCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPActionPerformed(evt);
            }
        });
        jPanel2.add(btnCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 143, 190, 40));

        pwdCCP.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        pwdCCP.setForeground(java.awt.Color.gray);
        pwdCCP.setText("Confirm New Password");
        pwdCCP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pwdCCP.setEchoChar((char)0);
        pwdCCP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pwdCCPCaretUpdate(evt);
            }
        });
        pwdCCP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdCCPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdCCPFocusLost(evt);
            }
        });
        pwdCCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdCCPMouseClicked(evt);
            }
        });
        pwdCCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdCCPKeyPressed(evt);
            }
        });
        jPanel2.add(pwdCCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 108, 310, -1));

        pwdCP.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        pwdCP.setForeground(java.awt.Color.gray);
        pwdCP.setText("New Password");
        pwdCP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pwdCP.setEchoChar((char)0);
        pwdCP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pwdCPCaretUpdate(evt);
            }
        });
        pwdCP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdCPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdCPFocusLost(evt);
            }
        });
        pwdCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdCPMouseClicked(evt);
            }
        });
        pwdCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdCPKeyPressed(evt);
            }
        });
        jPanel2.add(pwdCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 68, 310, -1));

        pwdOP.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        pwdOP.setForeground(java.awt.Color.gray);
        pwdOP.setText("Current Password");
        pwdOP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pwdOP.setEchoChar((char)0);
        pwdOP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pwdOPCaretUpdate(evt);
            }
        });
        pwdOP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdOPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdOPFocusLost(evt);
            }
        });
        pwdOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdOPMouseClicked(evt);
            }
        });
        pwdOP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdOPKeyPressed(evt);
            }
        });
        jPanel2.add(pwdOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 28, 310, -1));

        lblS_1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblS_1.setForeground(java.awt.Color.gray);
        lblS_1.setText("SHOW");
        lblS_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblS_1MouseClicked(evt);
            }
        });
        jPanel2.add(lblS_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 42, -1, -1));

        lblH_1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblH_1.setForeground(java.awt.Color.gray);
        lblH_1.setText("HIDE");
        lblH_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblH_1MouseClicked(evt);
            }
        });
        jPanel2.add(lblH_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 42, -1, -1));

        lblS_2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblS_2.setForeground(java.awt.Color.gray);
        lblS_2.setText("SHOW");
        lblS_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblS_2MouseClicked(evt);
            }
        });
        jPanel2.add(lblS_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 82, -1, -1));

        lblH_2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblH_2.setForeground(java.awt.Color.gray);
        lblH_2.setText("HIDE");
        lblH_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblH_2MouseClicked(evt);
            }
        });
        jPanel2.add(lblH_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 82, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/bottompart_4.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 370, 210));

        jPanel3.setBackground(new java.awt.Color(36, 56, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cPassTop_new.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cross-button.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        jPanel3.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 0, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 80));

        setSize(new java.awt.Dimension(370, 285));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-red.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPActionPerformed
        changePassword();
    }//GEN-LAST:event_btnCPActionPerformed

    private void pwdCPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdCPKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            changePassword();
        }
    }//GEN-LAST:event_pwdCPKeyPressed

    private void pwdCCPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdCCPKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            changePassword();
        }
    }//GEN-LAST:event_pwdCCPKeyPressed

    private void pwdCPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdCPFocusGained
        Color customColor = new Color(249, 234, 208);
        pwdCP.setText("");
        pwdCP.setText(newPass);
        pwdCP.setForeground(customColor);
        pwdCP.setEchoChar('\u25cf');
    }//GEN-LAST:event_pwdCPFocusGained

    private void pwdCPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdCPFocusLost
        pwdCP.setForeground(Color.GRAY);
        if (newPass.trim().length() != 0 && !newPass.trim().equals("New Password")) {
            pwdCCP.setText(confirmNewPass);
            pwdOP.setText(currentPass);
            pwdCP.setEchoChar('\u25cf');
        } else {
            pwdCP.setText("New Password");
            pwdCP.setEchoChar((char) 0);
            newPass = "";
        }
    }//GEN-LAST:event_pwdCPFocusLost

    private void pwdCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdCPMouseClicked
        pwdOP.setFocusable(true);
        pwdCP.setFocusable(true);
        pwdCCP.setFocusable(true);
        pwdCP.requestFocus();
    }//GEN-LAST:event_pwdCPMouseClicked

    private void pwdCCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdCCPMouseClicked
        pwdOP.setFocusable(true);
        pwdCCP.setFocusable(true);
        pwdCP.setFocusable(true);
        pwdCCP.requestFocus();
    }//GEN-LAST:event_pwdCCPMouseClicked

    private void pwdCCPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdCCPFocusGained
        Color customColor = new Color(249, 234, 208);
        pwdCCP.setText("");
        pwdCCP.setText(confirmNewPass);
        pwdCCP.setForeground(customColor);
        pwdCCP.setEchoChar('\u25cf');
    }//GEN-LAST:event_pwdCCPFocusGained

    private void pwdCCPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdCCPFocusLost
        pwdCCP.setForeground(Color.GRAY);
        if (confirmNewPass.trim().length() != 0 && !confirmNewPass.trim().equals("Confirm New Password")) {
            pwdCP.setText(newPass);
            pwdOP.setText(currentPass);
            pwdCCP.setEchoChar('\u25cf');
        } else {
            pwdCCP.setText("Confirm New Password");
            pwdCCP.setEchoChar((char) 0);
            confirmNewPass = "";
        }
    }//GEN-LAST:event_pwdCCPFocusLost

    private void pwdCPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pwdCPCaretUpdate
        newPass = pwdCP.getText();
    }//GEN-LAST:event_pwdCPCaretUpdate

    private void pwdCCPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pwdCCPCaretUpdate
        confirmNewPass = pwdCCP.getText();
    }//GEN-LAST:event_pwdCCPCaretUpdate

    private void lblS_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblS_1MouseClicked
//        showPassword1();
//        lblS_1.setVisible(false);
    }//GEN-LAST:event_lblS_1MouseClicked

    private void lblS_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblS_2MouseClicked
//        showPassword2();
//        lblS_2.setVisible(false);
    }//GEN-LAST:event_lblS_2MouseClicked

    private void lblH_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblH_1MouseClicked
//        hidePassword1();
    }//GEN-LAST:event_lblH_1MouseClicked

    private void lblH_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblH_2MouseClicked
//        hidePassword2();
    }//GEN-LAST:event_lblH_2MouseClicked

    private void pwdOPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pwdOPCaretUpdate
        currentPass = pwdOP.getText();
    }//GEN-LAST:event_pwdOPCaretUpdate

    private void pwdOPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdOPFocusGained
        Color customColor = new Color(249, 234, 208);
        pwdOP.setText("");
        pwdOP.setText(currentPass);
        pwdOP.setForeground(customColor);
        pwdOP.setEchoChar('\u25cf');
    }//GEN-LAST:event_pwdOPFocusGained

    private void pwdOPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdOPFocusLost
        pwdOP.setForeground(Color.GRAY);
        if (currentPass.trim().length() != 0 && !currentPass.trim().equals("Current Password")) {
            pwdCP.setText(newPass);
            pwdCCP.setText(confirmNewPass);
            pwdOP.setEchoChar('\u25cf');
        } else {
            pwdOP.setText("Current Password");
            pwdOP.setEchoChar((char) 0);
            currentPass = "";
        }
    }//GEN-LAST:event_pwdOPFocusLost

    private void pwdOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdOPMouseClicked
        pwdOP.setFocusable(true);
        pwdCP.setFocusable(true);
        pwdCCP.setFocusable(true);
        pwdOP.requestFocus();
    }//GEN-LAST:event_pwdOPMouseClicked

    private void pwdOPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdOPKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            changePassword();
        }
    }//GEN-LAST:event_pwdOPKeyPressed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        new MainFrameStudent().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePasswordUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCP;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblH_1;
    private javax.swing.JLabel lblH_2;
    private javax.swing.JLabel lblS_1;
    private javax.swing.JLabel lblS_2;
    private javax.swing.JPasswordField pwdCCP;
    private javax.swing.JPasswordField pwdCP;
    private javax.swing.JPasswordField pwdOP;
    // End of variables declaration//GEN-END:variables

    public void sqlconnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql:///dbAccount", "root", "");

        } catch (Exception e) {
            System.out.println("Connection Error: " + e);
        }
    }

    public void UpdatePassword(String username) {
        try {

            String sql = "update infologin set password = ? where username = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            MethodsLogIn li = new MethodsLogIn();
            String c = li.encrypt(pwdCCP.getText());
            pst.setString(1, c);
            pst.setString(2, username);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Password Changed!");
            audit(username, 0);
            MainFrameStudent mfu = new MainFrameStudent();
            mfu.setVisible(true);
            dispose();

        } catch (Exception e) {
            System.out.println("Error in UpdateStatus1: " + e);
        }
    }

    public void UpdateStatus1(String username) {

        try {

            String sql = "update infologin set pChange = ? where username = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, 1);
            pst.setString(2, username);
            pst.executeUpdate();
//            JOptionPane.showMessageDialog(rootPane, "Password Changed!");
//            MainFrameUser mfu = new MainFrameUser();
//            mfu.setVisible(true);
//            dispose();

        } catch (Exception e) {
            System.out.println("Error in UpdateStatus1: " + e);
        }
    }

    public void changePassword() {
        String username = getUsername();
        int c = check();
        if (c == 1) {
            try {
                Statement st = con.createStatement();
                String sql = "select * from infologin";
                ResultSet rs = st.executeQuery(sql);

                while (rs.next()) {
                    if (rs.getInt("status") == 1) {
                        if (rs.getInt("pChange") == 2) {
                            UpdateStatus1(username);
                            UpdatePassword(username);
                            break;
                        }
                    }
                }
            } catch (Exception e) {
                System.out.println("Error in changePassword: " + e);
            }
        }
    }

    public int check() {
        String pop = pwdOP.getText();
        String pcp = pwdCP.getText();
        String pccp = pwdCCP.getText();
        int c = 0;
        if (pop.trim().length() != 0 && !pop.equals("Current Password")) {
            if (pcp.trim().length() != 0 && !pcp.equals("New Password")) {

                if (pccp.trim().length() != 0 && !pccp.equals("Confirm New Password")) {
                    if (!pop.equals(password)) {
                        JOptionPane.showMessageDialog(rootPane, "Current password must be the same with your current password!");
                    } else if (!pcp.equals(pccp)) {
                        JOptionPane.showMessageDialog(rootPane, "New password and confirm new password must be the same!");
                    } else {
                        c = 1;
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Confirm new password must not be blank!");
                    pcp = "";
                    pccp = "";
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "New password must not be blank!");
                pcp = "";
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Current password must not be blank!");
            pop = "";
        }

//        if (pwdCP.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "New password should not be blank");
//        } else if (pwdCCP.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Confirm new password should not be blank");
//        } else if (!pwdCP.getText().equals(pwdCCP.getText())) {
//            JOptionPane.showMessageDialog(null, "New password and confirm new password should be the same");
//        } else {
//            c = 1;
//        }
        return c;
    }

    public void showPassword1() {
//        System.out.println(flag);
//        if (flag == 0) {
////                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/1667188461554126440-128.png"));
////                lblEye.setIcon(ImgIcon);
//            pwdCP.setEchoChar((char) 0);
////            lblS_1.setText("HIDE");
//            lblH_1.setVisible(true);
//            flag = 1;
//        }
//        else if (flag == 1) {
//
//            pwdCP.setEchoChar('\u25cf');
//            lblS_1.setVisible(true);
////            lblS_1.setb
//            flag = 0;
//        }
    }

    public void showPassword2() {
//        if (flag == 0) {
////                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/1667188461554126440-128.png"));
////                lblEye.setIcon(ImgIcon);
//            pwdCCP.setEchoChar((char) 0);
//            lblH_2.setVisible(true);
//            flag = 1;
//        }
//        else if (flag == 1) {
////                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/19318253741554126440-128.png"));
////                lblEye.setIcon(ImgIcon);
//            pwdCCP.setEchoChar('\u25cf');
//            lblS_2.setText("SHOW");
//            flag = 0;
//        }
    }

    public void hidePassword1() {
//        pwdCP.setEchoChar('\u25cf');
//        lblS_1.setVisible(true);
//        lblH_1.setVisible(false);
////            lblS_1.setb
//        flag = 0;
    }

    public void hidePassword2() {
//        pwdCCP.setEchoChar('\u25cf');
//        lblS_2.setVisible(true);
//        lblH_2.setVisible(false);
//        flag = 0;
    }

    public void setUsername(String x) {
        username = x;
    }

    public String getUsername() {
        return username;
    }

    public void setPass(String p) {
        password = p;
        System.out.println(p);
    }

     public void audit(String username, int i) {
        String format = "yyyy-MM-dd hh:mm:ss";
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat(format);
        System.out.println(sdf.format(date));
        String sql = "insert into audit values(?,?,?,?)";

        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, sdf.format(date));
            pst.setString(2, username);
            pst.setInt(3, i);
            pst.setString(4, "Changed Password");
            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
}
