/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Contents;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author kurtt
 */
public class LogIn extends javax.swing.JFrame {
//modal kurt modal ha

    MethodsLogIn ML = new MethodsLogIn();
    Methods M = new Methods();
    int flag;
    int x = 0;

    String username = "";
    String password = "";

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        ML.sqlconnect();
        ML.checkDay();
        M.usernames();
        txtUser.setFocusable(false);
        pwdPass.setFocusable(false);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        txtUser.setBackground(new java.awt.Color(0, 0, 0, 1));
        pwdPass.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnClr = new javax.swing.JButton();
        btnLI = new javax.swing.JButton();
        lblSP = new javax.swing.JLabel();
        pwdPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 56, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setForeground(new java.awt.Color(242, 242, 242));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cross-button.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/logo4.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 220));

        jPanel2.setBackground(new java.awt.Color(249, 234, 208));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClr.setBackground(new java.awt.Color(249, 234, 208));
        btnClr.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnClr.setForeground(new java.awt.Color(36, 56, 50));
        btnClr.setText("Clear");
        btnClr.setBorder(null);
        btnClr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClr.setFocusable(false);
        btnClr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClrMouseExited(evt);
            }
        });
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });
        jPanel2.add(btnClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, 40));

        btnLI.setBackground(new java.awt.Color(249, 234, 208));
        btnLI.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnLI.setForeground(new java.awt.Color(36, 56, 50));
        btnLI.setText("Log In");
        btnLI.setBorder(null);
        btnLI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLI.setFocusable(false);
        btnLI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLIMouseExited(evt);
            }
        });
        btnLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIActionPerformed(evt);
            }
        });
        jPanel2.add(btnLI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 80, 40));

        lblSP.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblSP.setForeground(new java.awt.Color(255, 255, 102));
        lblSP.setText("Show Password");
        lblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSPMouseClicked(evt);
            }
        });
        jPanel2.add(lblSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 110, -1));

        pwdPass.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        pwdPass.setForeground(java.awt.Color.gray);
        pwdPass.setText("Enter Password");
        pwdPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pwdPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pwdPass.setEchoChar((char)0);
        pwdPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pwdPassCaretUpdate(evt);
            }
        });
        pwdPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdPassFocusLost(evt);
            }
        });
        pwdPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdPassMouseClicked(evt);
            }
        });
        pwdPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdPassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdPassKeyReleased(evt);
            }
        });
        jPanel2.add(pwdPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 270, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/lock.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/user.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        txtUser.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtUser.setForeground(java.awt.Color.gray);
        txtUser.setText("Enter Username");
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtUser.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtUserCaretUpdate(evt);
            }
        });
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
        });
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 270, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel7.setText("Project Version: v1.0.5.5");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 327, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/middle9.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/logo5.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 480, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 350));

        setSize(new java.awt.Dimension(480, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
        txtUser.setText("Enter Username");
        pwdPass.setText("Enter Password");
        username = "";
        password = "";
        txtUser.setFocusable(false);
        pwdPass.setFocusable(false);
        pwdPass.setEchoChar((char) 0);
        lblSP.setText("Show Password");
    }//GEN-LAST:event_btnClrActionPerformed

    private void btnClrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClrMouseEntered
        Color customColor = new Color(119, 112, 99);
        btnClr.setBackground(customColor);
    }//GEN-LAST:event_btnClrMouseEntered

    private void btnClrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClrMouseExited
        Color customColor = new Color(249, 234, 208);
        btnClr.setBackground(customColor);
    }//GEN-LAST:event_btnClrMouseExited

    private void btnLIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLIMouseEntered
        Color customColor = new Color(119, 112, 99);
        btnLI.setBackground(customColor);
    }//GEN-LAST:event_btnLIMouseEntered

    private void btnLIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLIMouseExited
        Color customColor = new Color(249, 234, 208);
        btnLI.setBackground(customColor);
    }//GEN-LAST:event_btnLIMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        //kung di na maglalagay close button paalis nalang eto tysm
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        Color customColor = new Color(249, 234, 208);
        txtUser.setText("");
        txtUser.setText(username);
        txtUser.setForeground(customColor);

    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        txtUser.setForeground(Color.GRAY);
        if (username.trim().length() != 0 && !username.equals("Enter Username")) {// may trim dito kanina
            txtUser.setText(username);
        } else {
            txtUser.setText("Enter Username");
            username = "";
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void pwdPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPassFocusGained
        Color customColor = new Color(249, 234, 208);
        pwdPass.setText("");
        pwdPass.setText(password);
        pwdPass.setForeground(customColor);
        pwdPass.setEchoChar('\u25cf');

    }//GEN-LAST:event_pwdPassFocusGained

    private void pwdPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPassFocusLost
        pwdPass.setForeground(Color.GRAY);
        if (password.trim().length() != 0 && !password.trim().equals("Enter Password")) {
            txtUser.setText(username);
            pwdPass.setEchoChar('\u25cf');
        } else {
            pwdPass.setText("Enter Password");
            pwdPass.setEchoChar((char) 0);
            password = "";
        }
    }//GEN-LAST:event_pwdPassFocusLost

    private void txtUserCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtUserCaretUpdate
        username = txtUser.getText();
    }//GEN-LAST:event_txtUserCaretUpdate

    private void pwdPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pwdPassCaretUpdate
        password = pwdPass.getText();
    }//GEN-LAST:event_pwdPassCaretUpdate

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        txtUser.setFocusable(true);
        pwdPass.setFocusable(true);
        txtUser.requestFocus();
    }//GEN-LAST:event_txtUserMouseClicked

    private void pwdPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdPassMouseClicked
        txtUser.setFocusable(true);
        pwdPass.setFocusable(true);
        pwdPass.requestFocus();
    }//GEN-LAST:event_pwdPassMouseClicked

    private void btnLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIActionPerformed
        ML.existing(txtUser.getText(), password, pwdPass.getText());
        if (ML.choice() > 0) {
            dispose();
        }
    }//GEN-LAST:event_btnLIActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-red.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseExited

    private void lblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSPMouseClicked
        ML.showPass(lblSP,pwdPass);
    }//GEN-LAST:event_lblSPMouseClicked

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        ML.loginKeyPress(evt, username, password, pwdPass.getText());
        if (ML.choice() > 0) {
            dispose();
        }
    }//GEN-LAST:event_txtUserKeyPressed

    private void pwdPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPassKeyPressed
        ML.loginKeyPress(evt, username, password, pwdPass.getText());
        if (ML.choice() > 0) {
            dispose();
        }
    }//GEN-LAST:event_pwdPassKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        ML.powerUser(evt);
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        ML.powerUserReleased(evt);
    }//GEN-LAST:event_formKeyReleased

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        ML.powerUserReleased(evt);
    }//GEN-LAST:event_txtUserKeyReleased

    private void pwdPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPassKeyReleased
        ML.powerUserReleased(evt);
    }//GEN-LAST:event_pwdPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MethodsLogIn.startUp();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnLI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSP;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
