/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Contents;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.security.Key;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import sun.misc.BASE64Decoder;
import sun.misc.BASE64Encoder;

/**
 *
 * @author kurtt
 */
public class LogIn extends javax.swing.JFrame {
//modal kurt modal ha

    int flag;
    int x = 0;
    String username = "";
    String password = "";
    Connection con;
    final String ALGORITHM = "AES";
    final String KEY = "1Hbfh667adfDEJ78";

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        sqlconnect();
        initComponents();
        checkDay();
        txtUser.setFocusable(false);
        pwdPass.setFocusable(false);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        txtUser.setBackground(new java.awt.Color(0, 0, 0, 1));
        pwdPass.setBackground(new java.awt.Color(0, 0, 0, 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnClr = new javax.swing.JButton();
        btnLI = new javax.swing.JButton();
        lblSP = new javax.swing.JLabel();
        pwdPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 56, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setForeground(new java.awt.Color(242, 242, 242));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cross-button.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/logo4.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 220));

        jPanel2.setBackground(new java.awt.Color(249, 234, 208));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClr.setBackground(new java.awt.Color(249, 234, 208));
        btnClr.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnClr.setForeground(new java.awt.Color(36, 56, 50));
        btnClr.setText("Clear");
        btnClr.setBorder(null);
        btnClr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClr.setFocusable(false);
        btnClr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClrMouseExited(evt);
            }
        });
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });
        jPanel2.add(btnClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, 40));

        btnLI.setBackground(new java.awt.Color(249, 234, 208));
        btnLI.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnLI.setForeground(new java.awt.Color(36, 56, 50));
        btnLI.setText("Log In");
        btnLI.setBorder(null);
        btnLI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLI.setFocusable(false);
        btnLI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLIMouseExited(evt);
            }
        });
        btnLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIActionPerformed(evt);
            }
        });
        jPanel2.add(btnLI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 80, 40));

        lblSP.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblSP.setForeground(new java.awt.Color(255, 255, 102));
        lblSP.setText("Show Password");
        lblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSPMouseClicked(evt);
            }
        });
        jPanel2.add(lblSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 110, -1));

        pwdPass.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        pwdPass.setForeground(java.awt.Color.gray);
        pwdPass.setText("Enter Password");
        pwdPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pwdPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pwdPass.setEchoChar((char)0);
        pwdPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pwdPassCaretUpdate(evt);
            }
        });
        pwdPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdPassFocusLost(evt);
            }
        });
        pwdPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdPassMouseClicked(evt);
            }
        });
        pwdPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdPassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdPassKeyReleased(evt);
            }
        });
        jPanel2.add(pwdPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 270, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/lock.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/user.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        txtUser.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtUser.setForeground(java.awt.Color.gray);
        txtUser.setText("Enter Username");
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtUser.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtUserCaretUpdate(evt);
            }
        });
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
        });
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 270, -1));

        jLabel7.setText("Project Version: v1.0.5");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/middle8.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/logo5.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 480, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 350));

        setSize(new java.awt.Dimension(480, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
        txtUser.setText("Enter Username");
        pwdPass.setText("Enter Password");
        username = "";
        password = "";
        txtUser.setFocusable(false);
        pwdPass.setFocusable(false);
        pwdPass.setEchoChar((char) 0);
        lblSP.setText("Show Password");
    }//GEN-LAST:event_btnClrActionPerformed

    private void btnClrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClrMouseEntered
        Color customColor = new Color(119, 112, 99);
        btnClr.setBackground(customColor);
    }//GEN-LAST:event_btnClrMouseEntered

    private void btnClrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClrMouseExited
        Color customColor = new Color(249, 234, 208);
        btnClr.setBackground(customColor);
    }//GEN-LAST:event_btnClrMouseExited

    private void btnLIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLIMouseEntered
        Color customColor = new Color(119, 112, 99);
        btnLI.setBackground(customColor);
    }//GEN-LAST:event_btnLIMouseEntered

    private void btnLIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLIMouseExited
        Color customColor = new Color(249, 234, 208);
        btnLI.setBackground(customColor);
    }//GEN-LAST:event_btnLIMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        //kung di na maglalagay close button paalis nalang eto tysm
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        Color customColor = new Color(249, 234, 208);
        txtUser.setText("");
        txtUser.setText(username);
        txtUser.setForeground(customColor);

    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        txtUser.setForeground(Color.GRAY);
        if (username.trim().length() != 0 && !username.equals("Enter Username")) {// may trim dito kanina
            txtUser.setText(username);
        } else {
            txtUser.setText("Enter Username");
            username = "";
        }

    }//GEN-LAST:event_txtUserFocusLost

    private void pwdPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPassFocusGained
        Color customColor = new Color(249, 234, 208);
        pwdPass.setText("");
        pwdPass.setText(password);
        pwdPass.setForeground(customColor);
        pwdPass.setEchoChar('\u25cf');

    }//GEN-LAST:event_pwdPassFocusGained

    private void pwdPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPassFocusLost
        pwdPass.setForeground(Color.GRAY);
        if (password.trim().length() != 0 && !password.trim().equals("Enter Username")) {
            txtUser.setText(username);
            pwdPass.setEchoChar('\u25cf');
        } else {
            pwdPass.setText("Enter Password");
            pwdPass.setEchoChar((char) 0);
            password = "";
        }

    }//GEN-LAST:event_pwdPassFocusLost

    private void txtUserCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtUserCaretUpdate
        username = txtUser.getText();
    }//GEN-LAST:event_txtUserCaretUpdate

    private void pwdPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pwdPassCaretUpdate
        password = pwdPass.getText();
    }//GEN-LAST:event_pwdPassCaretUpdate

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        txtUser.setFocusable(true);
        pwdPass.setFocusable(true);
        txtUser.requestFocus();
    }//GEN-LAST:event_txtUserMouseClicked

    private void pwdPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdPassMouseClicked
        txtUser.setFocusable(true);
        pwdPass.setFocusable(true);
        pwdPass.requestFocus();
    }//GEN-LAST:event_pwdPassMouseClicked

    private void btnLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIActionPerformed
        checkStatus();
    }//GEN-LAST:event_btnLIActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-red.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseExited

    private void lblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSPMouseClicked
        showPassword();
    }//GEN-LAST:event_lblSPMouseClicked

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkStatus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ALT && x == 0) {
            x++;

        }
        if (evt.getKeyCode() == KeyEvent.VK_F1 && x == 1) {
            x++;

        }
        if (x == 2) {
            JOptionPane.showMessageDialog(rootPane, "Power User....");
            new MainFrameAdmin().setVisible(true);
            dispose();
            x = 0;
        }
    }//GEN-LAST:event_txtUserKeyPressed

    private void pwdPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkStatus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ALT && x == 0) {
            x++;

        }
        if (evt.getKeyCode() == KeyEvent.VK_F1 && x == 1) {
            x++;

        }
        if (x == 2) {
            JOptionPane.showMessageDialog(rootPane, "Power User....");
            new MainFrameAdmin().setVisible(true);
            dispose();
            x = 0;
        }
    }//GEN-LAST:event_pwdPassKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ALT && x == 0) {
            x++;

        }
        if (evt.getKeyCode() == KeyEvent.VK_F1 && x == 1) {
            x++;

        }
        if (x == 2) {
            JOptionPane.showMessageDialog(rootPane, "Power User....");
            new MainFrameAdmin().setVisible(true);
            dispose();
            x = 0;
        }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ALT && x > 0) {
            x--;

        }
    }//GEN-LAST:event_formKeyReleased

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ALT && x > 0) {
            x--;

        }


    }//GEN-LAST:event_txtUserKeyReleased

    private void pwdPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPassKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ALT && x > 0) {
            x--;
        }
    }//GEN-LAST:event_pwdPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int i = 0;
                String sql = "select * from infologin";

                try {
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql:///dbAccount", "root", "");
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery(sql);

                    while (rs.next()) {
                        if (rs.getInt("status") == 1) {
                            if (rs.getInt("pChange") == 0) {
                                ChangePassword cp = new ChangePassword();
                                cp.setVisible(true);
                                new LogIn().setVisible(false);
                                i = 0;
                                break;
                            } else {
                                MainFrameUser mf = new MainFrameUser();
                                mf.setVisible(true);
                                new LogIn().setVisible(false);
                                i = 0;
                                break;
                            }

                        } else {
                            i = 1;

                        }
                    }
                    if (i == 1) {
                        new LogIn().setVisible(true);
                    }

                } catch (Exception e) {
                    System.out.println("Error CheckStatus: " + e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnLI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSP;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    public void sqlconnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql:///dbAccount", "root", "");

        } catch (Exception e) {
            System.out.println("Connection Error: " + e);
        }
    }

    public Key generateKey() throws Exception {
        Key key = new SecretKeySpec(KEY.getBytes(), ALGORITHM);
        return key;
    }

    public String encrypt(String value) {
        String b64value = "";
        try {
            Key key = generateKey();
            Cipher cipher = Cipher.getInstance(ALGORITHM);
            cipher.init(Cipher.ENCRYPT_MODE, key);
            byte[] encryptedByteValue = cipher.doFinal(value.getBytes("utf-8"));
            b64value = new BASE64Encoder().encode(encryptedByteValue);
        } catch (Exception e) {
            System.err.println("Error in Encrypt: " + e);
        }
        return b64value;
    }

    public String decrypt(String value) {
        String decryptedValue = "";
        try {
            Key key = generateKey();
            Cipher cipher = Cipher.getInstance(ALGORITHM);
            cipher.init(Cipher.DECRYPT_MODE, key);
            byte[] decryptedValue64 = new BASE64Decoder().decodeBuffer(value);
            byte[] decryptedByteValue = cipher.doFinal(decryptedValue64);
            decryptedValue = new String(decryptedByteValue, "utf-8");
        } catch (Exception e) {
            System.err.println("Error in Decrypt: " + e);
        }
        return decryptedValue;
    }

    public void login() {
        int x = 0;
        String username2 = txtUser.getText();
        String password2 = pwdPass.getText();

        try {
            Statement st = con.createStatement();
            String sql = "select * from infologin";
            ResultSet rs = st.executeQuery(sql);

            if (username2.trim().length() != 0 && !username2.equals("Enter Username")) {

                if (password2.trim().length() != 0 && !password2.equals("Enter Password")) {
                    while (rs.next()) {

                        if (username2.equals(rs.getString("username")) && password2.equals(decrypt(rs.getString("password")))) {

                            if (rs.getInt("block") == 3) {
                                blockable();
                                x = 0;
                                break;
                            } else {
                                checkAdmin();
                                txtUser.setFocusable(false);
                                pwdPass.setFocusable(false);
                                x = 0;
                                resetBlock();
                                break;
                            }
                        } else if (username2.equals(rs.getString("username")) && !password.equals(decrypt(rs.getString("password")))) {
                            x = 0;
                            blockable();
                            break;

                        } else {
                            x = 1;
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Password must not be blank!");
                    password = "";
                    username = "";
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Username must not be blank!");
                username = "";
            }

            if (x == 1) {
                JOptionPane.showMessageDialog(rootPane, "Username does not exist");
            }
        } catch (Exception e) {
            System.out.println("Error in Login: " + e);
        }

    }

    public void checkAdmin() {
        String username2 = txtUser.getText();
        try {
            Statement st = con.createStatement();
            String sql = "select * from infologin";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                if (username2.equals(rs.getString("username"))) {
                    if (rs.getInt("status") == 2) {
                        JOptionPane.showMessageDialog(rootPane, "An Admin Is Already Signed In!");
                    } else if (rs.getInt("status") == 1) {
                        JOptionPane.showMessageDialog(rootPane, "An Account Is Already Signed In!");
                    } else {
                        UpdateStatus1(rs.getInt("isAdmin"));
                    }
                    break;
                }
            }

        } catch (Exception e) {
            System.out.println("Error in checkAdmin: " + e);
        }
    }

    public void UpdateStatus1(int x) {
        String username = txtUser.getText();

        try {
            if (x == 1) {
                String sql = "update infologin set status = ? where username = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, 2);
                pst.setString(2, username);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Welcome Admin");
                MainFrameAdmin mfa = new MainFrameAdmin();
                mfa.setVisible(true);
                dispose();
            } else {
                String sql = "update infologin set status = ? where username = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, 1);
                pst.setString(2, username);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Successfully Logged In \n       Welcome " + username + "!");
                changePassword();
                dispose();
            }

        } catch (Exception e) {
            System.out.println("Error in UpdateStatus1: " + e);
        }
    }

    public void resetBlock() {
        try {
            String sql = "update infologin set block = ? where block < ?";
            PreparedStatement pst;
            pst = con.prepareStatement(sql);
            pst.setInt(1, 0);
            pst.setInt(2, 3);

            pst.executeUpdate();

        } catch (Exception e) {
            System.out.println("Error in resetBlock: " + e);
        }

    }

    public void resetBlock2() {
        try {
            String sql = "update infologin set block = ?";
            PreparedStatement pst;
            pst = con.prepareStatement(sql);
            pst.setInt(1, 0);

            pst.executeUpdate();

        } catch (Exception e) {
            System.out.println("Error in resetBlock: " + e);
        }

    }

    public void updateDate(String date) {
        try {
            String sql = "update infologin set date = ?";
            PreparedStatement pst;
            pst = con.prepareStatement(sql);
            pst.setString(1, date);

            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println("Error date:" + e);
        }
    }

    public void checkDay() {
        String sql = "select date from infologin";
        Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                if (!rs.getString(1).equals(ft.format(date))) {
                    resetBlock2();
                    updateDate(ft.format(date));
                    System.out.println(rs.getString(1));
                    JOptionPane.showMessageDialog(rootPane, "All Blocks From Yesterday Has Been Reverted");
                    break;
                }
            }
        } catch (Exception e) {
            System.out.println("Error checkDay: " + e);
        }
    }

    public void checkStatus() {
        int i = 0;

        String sql = "select status from infologin";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                if (rs.getInt(1) == 1) {
                    JOptionPane.showMessageDialog(rootPane, "An Account Is Already Signed In!");
                    i = 1;
                    break;
                } else {
                    i = 0;
                }
            }

            if (i == 0) {
                login();
            }
        } catch (Exception e) {
            System.out.println("Error checkStatus: " + e);
        }
    }

    public void showPassword() {

        if (flag == 0) {
//                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/1667188461554126440-128.png"));
//                lblEye.setIcon(ImgIcon);
            pwdPass.setEchoChar((char) 0);
            lblSP.setText("Hide Password");
            flag = 1;
        } else if (flag == 1) {
//                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/19318253741554126440-128.png"));
//                lblEye.setIcon(ImgIcon);
            pwdPass.setEchoChar('\u25cf');
            lblSP.setText("Show Password");
            flag = 0;
        }
    }

    public void blockable() {
        String username2 = txtUser.getText();
        try {
            Statement st = con.createStatement();
            String sql = "select * from infologin";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                if (username2.equals(rs.getString("username"))) {
                    if (rs.getInt("block") == 3) {
                        JOptionPane.showMessageDialog(rootPane, "This Account Is Already Blocked!");
                        break;
                    } else if (rs.getInt("block") + 1 == 3) {
                        JOptionPane.showMessageDialog(rootPane, "This Account Has Been Blocked!");
                        blockable2(rs.getInt("block") + 1, username2);
                        break;
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Username and Password did not match");
                        blockable2(rs.getInt("block") + 1, username2);
                        break;
                    }
                }

            }

        } catch (Exception e) {
            System.out.println("Error in blockable: " + e);
        }
    }

    public void blockable2(int x, String username2) {

        try {
            String sql = "update infologin set block = ? where username = ?";
            PreparedStatement pst;
            pst = con.prepareStatement(sql);
            pst.setInt(1, x);
            pst.setString(2, username2);

            pst.executeUpdate();
            System.out.println("hi");
        } catch (Exception e) {
            System.out.println("Error in blockable2: " + e);
        }
    }

    public void changePassword() {
        String username2 = txtUser.getText();
        try {
            Statement st = con.createStatement();
            String sql = "select * from infologin";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                if (username2.equals(rs.getString("username"))) {
                    if (rs.getInt("pChange") == 0) {
                        ChangePassword cp = new ChangePassword();
                        cp.setVisible(true);
                        dispose();
                        break;
                    } else {
                        MainFrameUser mfu = new MainFrameUser();
                        mfu.setVisible(true);
                        dispose();
                        break;
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("Error in changePassword: " + e);
        }
    }
}
