/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Contents;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kurtt
 */
public class MainFrameUser extends javax.swing.JFrame {

    int flag = 0;
    Connection con;
    String username;
    String password = "", p = "";
    Color c = new Color(0, 0, 0, 1);
    Color customColor = new Color(36, 56, 50);
    int j = 1;

    /**
     * Creates new form MainFrame
     */
    public MainFrameUser() {
        initComponents();
//        functions();
        txtUser.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtPass.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain_2 = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        pnlRight_1 = new javax.swing.JPanel();
        lblEditPass = new javax.swing.JLabel();
        lblEditUser = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        lblAI = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pnlRight_2 = new javax.swing.JPanel();
        lblLogo1 = new javax.swing.JLabel();
        pnlRight_3 = new javax.swing.JPanel();
        lblLogo2 = new javax.swing.JLabel();
        pnlRight_4 = new javax.swing.JPanel();
        lblB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLogo3 = new javax.swing.JLabel();
        pnlMain_1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlLeft_4 = new javax.swing.JPanel();
        lblR_4 = new javax.swing.JLabel();
        pnlLeft_3 = new javax.swing.JPanel();
        lblR_3 = new javax.swing.JLabel();
        pnlLeft_2 = new javax.swing.JPanel();
        lblR_2 = new javax.swing.JLabel();
        pnlLeft_1 = new javax.swing.JPanel();
        lblR_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain_2.setBackground(new java.awt.Color(249, 234, 208));
        pnlMain_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cross-button-green.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        pnlMain_2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 5, -1, -1));

        pnlRight_1.setBackground(new java.awt.Color(249, 234, 208));
        pnlRight_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEditPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/edit.png"))); // NOI18N
        lblEditPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditPassMouseClicked(evt);
            }
        });
        pnlRight_1.add(lblEditPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 303, -1, -1));

        lblEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/edit.png"))); // NOI18N
        lblEditUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditUserMouseClicked(evt);
            }
        });
        pnlRight_1.add(lblEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 263, -1, -1));

        lblUser.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Username:");
        pnlRight_1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 260, -1, -1));

        lblPass.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Password:");
        pnlRight_1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 300, -1, -1));

        txtUser.setEditable(false);
        txtUser.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlRight_1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 260, 180, -1));

        txtPass.setEditable(false);
        txtPass.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlRight_1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 300, 180, -1));

        lblAI.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        lblAI.setForeground(new java.awt.Color(255, 255, 255));
        lblAI.setText("Account Information");
        pnlRight_1.add(lblAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 190, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/panelmiddle_5.png"))); // NOI18N
        pnlRight_1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblN.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        pnlRight_1.add(lblN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pnlRight_2.setBackground(new java.awt.Color(197, 186, 165));
        pnlRight_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_2.add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        pnlRight_3.setBackground(new java.awt.Color(249, 234, 208));
        pnlRight_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_3.add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        pnlRight_4.setBackground(new java.awt.Color(197, 186, 165));
        pnlRight_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblB.setText("Log Out");
        lblB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBMouseClicked(evt);
            }
        });
        pnlRight_4.add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        jLabel2.setText("User");
        pnlRight_4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_4.add(lblLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        getContentPane().add(pnlMain_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 600));

        pnlMain_1.setBackground(new java.awt.Color(36, 56, 50));
        pnlMain_1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                pnlMain_1MouseWheelMoved(evt);
            }
        });
        pnlMain_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/mainFrameBPart.6.png"))); // NOI18N
        pnlMain_1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/line_2.png"))); // NOI18N
        pnlMain_1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/line_2.png"))); // NOI18N
        pnlMain_1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 435, -1, -1));

        pnlLeft_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_4.setForeground(new java.awt.Color(255, 255, 255));
        lblR_4.setText("ABOUT");
        lblR_4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_4FocusLost(evt);
            }
        });
        lblR_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_4MouseClicked(evt);
            }
        });
        pnlLeft_4.add(lblR_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 180, 40));

        pnlLeft_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_3.setForeground(new java.awt.Color(255, 255, 255));
        lblR_3.setText("CONTACT");
        lblR_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_3FocusLost(evt);
            }
        });
        lblR_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_3MouseClicked(evt);
            }
        });
        pnlLeft_3.add(lblR_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, 40));

        pnlLeft_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_2.setForeground(new java.awt.Color(255, 255, 255));
        lblR_2.setText("SERVICES");
        lblR_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_2FocusLost(evt);
            }
        });
        lblR_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_2MouseClicked(evt);
            }
        });
        pnlLeft_2.add(lblR_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        pnlLeft_1.setBackground(java.awt.Color.gray);
        pnlLeft_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_1.setForeground(new java.awt.Color(255, 255, 255));
        lblR_1.setText("HOME");
        lblR_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_1FocusLost(evt);
            }
        });
        lblR_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_1MouseClicked(evt);
            }
        });
        pnlLeft_1.add(lblR_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        getContentPane().add(pnlMain_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-green.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-red.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        Closer();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void lblBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBMouseClicked
        LogOut(jLabel2.getText() + "");
    }//GEN-LAST:event_lblBMouseClicked

    private void lblR_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_1MouseClicked
        flag = 1;
        lblR_1.requestFocus();
        pnlRight_1.setVisible(true);
        lblN.setText("Welcome, " + jLabel2.getText());
        j = 1;
    }//GEN-LAST:event_lblR_1MouseClicked

    private void lblR_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_2MouseClicked
        flag = 2;
        lblR_2.requestFocus();
        pnlRight_2.setVisible(true);
        j = 2;
    }//GEN-LAST:event_lblR_2MouseClicked

    private void lblR_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_3MouseClicked
        flag = 3;
        lblR_3.requestFocus();
        pnlRight_3.setVisible(true);
        j = 3;
    }//GEN-LAST:event_lblR_3MouseClicked

    private void lblR_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_1FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_1FocusGained

    private void lblR_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_1FocusLost

    }//GEN-LAST:event_lblR_1FocusLost

    private void lblR_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_2FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_2FocusGained

    private void lblR_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_2FocusLost

    }//GEN-LAST:event_lblR_2FocusLost

    private void lblR_3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_3FocusGained
        Changer(flag);

    }//GEN-LAST:event_lblR_3FocusGained

    private void lblR_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_3FocusLost

    }//GEN-LAST:event_lblR_3FocusLost

    private void lblR_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_4MouseClicked
        flag = 4;
        lblR_4.requestFocus();
        pnlRight_4.setVisible(true);
        j = 4;
    }//GEN-LAST:event_lblR_4MouseClicked

    private void lblR_4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_4FocusLost

    }//GEN-LAST:event_lblR_4FocusLost

    private void lblR_4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_4FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_4FocusGained

    private void pnlMain_1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_pnlMain_1MouseWheelMoved
        if (evt.getWheelRotation() == 1) {
            j++;
            if (j >= 6) {
                j = 6;
            }
            System.out.println("up");
            Changer(j);
            FrameSwitch(j);
            System.out.println(j);

        } else if (evt.getWheelRotation() == -1) {
            j--;
            if (j <= 1) {
                j = 1;
            }
            System.out.println("Mouse wheel down");
            Changer(j);
            FrameSwitch(j);
            System.out.println(j);

        }

    }//GEN-LAST:event_pnlMain_1MouseWheelMoved

    private void lblEditUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditUserMouseClicked
        ChangeUsername cu = new ChangeUsername();
        cu.setPassword(password);
        cu.setVisible(true);
        cu.setAlwaysOnTop(true);
        dispose();
    }//GEN-LAST:event_lblEditUserMouseClicked

    private void lblEditPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditPassMouseClicked
        
    }//GEN-LAST:event_lblEditPassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameUser().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAI;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblEditPass;
    private javax.swing.JLabel lblEditUser;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblR_1;
    private javax.swing.JLabel lblR_2;
    private javax.swing.JLabel lblR_3;
    private javax.swing.JLabel lblR_4;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlLeft_1;
    private javax.swing.JPanel pnlLeft_2;
    private javax.swing.JPanel pnlLeft_3;
    private javax.swing.JPanel pnlLeft_4;
    private javax.swing.JPanel pnlMain_1;
    private javax.swing.JPanel pnlMain_2;
    private javax.swing.JPanel pnlRight_1;
    private javax.swing.JPanel pnlRight_2;
    private javax.swing.JPanel pnlRight_3;
    private javax.swing.JPanel pnlRight_4;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    public void sqlconnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql:///dbAccount", "root", "");

        } catch (Exception e) {
            System.out.println("Connection Error: " + e);
        }
    }

    public void saveUsername(String x) {
        username = x;
//wala pa function to nag iisip pako kung ano mas magandang approach
    }

    public void LogOut(String username) {

        String sql = "update infologin set status = ? where username = ?";
        sqlconnect();
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, 0);
            pst.setString(2, username);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Successfully Signed Out");
            LogIn li = new LogIn();
            li.setVisible(true);
            dispose();
        } catch (Exception e) {
            System.out.println("Error us2: " + e);
        }
    }

    public void Closer() {

        String sql = "update infologin set status = ? where status = ?";
        sqlconnect();
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, 0);
            pst.setInt(2, 1);
            pst.executeUpdate();
            System.exit(0);
        } catch (Exception e) {
            System.exit(0);
        }
    }

    public void functions() {
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
//        pnlLeft_1.setBackground(c);
        pnlLeft_2.setBackground(c);
        pnlLeft_3.setBackground(c);
        pnlLeft_4.setBackground(c);
        pnlRight_1.setVisible(true);
        pnlRight_2.setVisible(false);
        pnlRight_3.setVisible(false);
        pnlRight_4.setVisible(false);
        txtUser.setText(jLabel2.getText());
        for (int i = 0; i < password.length(); i++) {
            p = p + "•";
        }
        txtPass.setText(p);
        Changer(1);
    }

    public void Changer(int a) {
        switch (a) {
            case 1:
                lblN.setText("Welcome, " + jLabel2.getText());
                pnlLeft_1.setBackground(Color.GRAY);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                flag = 0;
                break;
            case 2:
                pnlLeft_2.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                flag = 0;
                break;
            case 3:
                pnlLeft_3.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                flag = 0;
                break;
            case 4:
                pnlLeft_4.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                flag = 0;
                break;
            default:
                break;

        }
    }

    public void FrameSwitch(int j) {
        switch (j) {
            case 1:
                lblR_1.requestFocus();
                pnlRight_1.setVisible(true);
                break;
            case 2:
                lblR_2.requestFocus();
                pnlRight_2.setVisible(true);
                break;
            case 3:
                lblR_3.requestFocus();
                pnlRight_3.setVisible(true);
                break;
            case 4:
                lblR_4.requestFocus();
                pnlRight_4.setVisible(true);
                break;
            default:
                break;
        }
    }

    public void getUsername(String x) {
        jLabel2.setText(x);
        functions();
    }
    
    public void setPassword (String y) {
        password = y;
    }
}
