/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Contents;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.Key;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sun.misc.BASE64Decoder;

/**
 *
 * @author kurtt
 */
public class MainFrameStudent extends javax.swing.JFrame {

    int flag = 0;
    Connection con;
    String username;
    String password = "", p = "";
    Color c = new Color(0, 0, 0, 1);
    Color customColor = new Color(36, 56, 50);
    int j = 1;
    String path;
    int cert = 0;
    int sw = 0;

    /**
     * Creates new form MainFrame
     */
    public MainFrameStudent() {
        initComponents();
//        functions();
        txtUser.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtPass.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtLRN.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtLN.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtStrand.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtName.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtBirthD.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtGen.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtGL.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtSection.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtReligion.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtSex.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtAddress.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtContact.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtFather.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtFOccu.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtMother.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtMOccu.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtGuardian.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtGOccu.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtPC.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtPCCon.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt4Ps.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtWorking.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtNature.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtNameEmp.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtWorkAd.setBackground(new java.awt.Color(0, 0, 0, 1));
        lblC.setVisible(false);
        lblP.setVisible(false);
        Methods m = new Methods();
        m.usernames();
        try {
            //create the font to use. Specify the size!
            Font customFont = Font.createFont(Font.TRUETYPE_FONT, new File("src\\Fonts\\Santana-BlackCondensed.ttf")).deriveFont(45f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            //register the font
            ge.registerFont(customFont);
            lblN.setFont(customFont);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (FontFormatException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain_2 = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        pnlRight_1 = new javax.swing.JPanel();
        lblHomePage = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pnlRight_2 = new javax.swing.JPanel();
        lblCOUP = new javax.swing.JLabel();
        lblCOG = new javax.swing.JLabel();
        lblCOR = new javax.swing.JLabel();
        lblCOGM = new javax.swing.JLabel();
        lblS2 = new javax.swing.JLabel();
        lblS1 = new javax.swing.JLabel();
        lblPrev = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        pnlRight_3 = new javax.swing.JPanel();
        lblLogo2 = new javax.swing.JLabel();
        pnlRight_4 = new javax.swing.JPanel();
        lblP1 = new javax.swing.JLabel();
        lblN2 = new javax.swing.JLabel();
        lblUpload = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        pnlP_1 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        lblEditPass = new javax.swing.JLabel();
        lblEditUser = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblLogo5 = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlP_2 = new javax.swing.JPanel();
        lblBD = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGL = new javax.swing.JTextField();
        lblSection = new javax.swing.JLabel();
        txtStrand = new javax.swing.JTextField();
        lblLRN = new javax.swing.JLabel();
        txtSY = new javax.swing.JTextField();
        lblSY = new javax.swing.JLabel();
        txtLRN = new javax.swing.JTextField();
        lblGen = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtSection = new javax.swing.JTextField();
        lblGL = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        lblStrand = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtSex = new javax.swing.JTextField();
        txtR = new javax.swing.JTextField();
        lblSex = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        txtCN = new javax.swing.JTextField();
        lblReligion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLogo4 = new javax.swing.JLabel();
        pnlP_3 = new javax.swing.JPanel();
        lblBD1 = new javax.swing.JLabel();
        txtMO = new javax.swing.JTextField();
        txtMN = new javax.swing.JTextField();
        lblLRN1 = new javax.swing.JLabel();
        txtFO = new javax.swing.JTextField();
        lblSY1 = new javax.swing.JLabel();
        txtFN = new javax.swing.JTextField();
        lblGen1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        txtGN = new javax.swing.JTextField();
        txtGO = new javax.swing.JTextField();
        lblStrand1 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        txtPC = new javax.swing.JTextField();
        lblContact1 = new javax.swing.JLabel();
        txtPCCon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblLogo6 = new javax.swing.JLabel();
        pnlP_4 = new javax.swing.JPanel();
        lblLRN2 = new javax.swing.JLabel();
        btnUI = new javax.swing.JButton();
        txt4Ps = new javax.swing.JTextField();
        lblSY2 = new javax.swing.JLabel();
        txtWorking = new javax.swing.JTextField();
        lblStrand2 = new javax.swing.JLabel();
        txtNature = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        lblBD2 = new javax.swing.JLabel();
        txtWorkAd = new javax.swing.JTextField();
        txtNameEmp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblLogo7 = new javax.swing.JLabel();
        pnlRight_5 = new javax.swing.JPanel();
        lblP = new javax.swing.JLabel();
        lblN1 = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblLogo3 = new javax.swing.JLabel();
        pnlMain_1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlLeft_5 = new javax.swing.JPanel();
        lblR_5 = new javax.swing.JLabel();
        pnlLeft_4 = new javax.swing.JPanel();
        lblR_4 = new javax.swing.JLabel();
        pnlLeft_3 = new javax.swing.JPanel();
        lblR_3 = new javax.swing.JLabel();
        pnlLeft_2 = new javax.swing.JPanel();
        lblR_2 = new javax.swing.JLabel();
        pnlLeft_1 = new javax.swing.JPanel();
        lblR_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain_2.setBackground(new java.awt.Color(249, 234, 208));
        pnlMain_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cross-button-green.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        pnlMain_2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 5, -1, -1));

        pnlRight_1.setBackground(new java.awt.Color(249, 234, 208));
        pnlRight_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/homePage.png"))); // NOI18N
        pnlRight_1.add(lblHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pnlRight_2.setBackground(new java.awt.Color(197, 186, 165));
        pnlRight_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCOUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/file_1.png"))); // NOI18N
        lblCOUP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblCOUPFocusGained(evt);
            }
        });
        lblCOUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCOUPMouseClicked(evt);
            }
        });
        pnlRight_2.add(lblCOUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 347, -1, -1));

        lblCOG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/file_1.png"))); // NOI18N
        lblCOG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblCOGFocusGained(evt);
            }
        });
        lblCOG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCOGMouseClicked(evt);
            }
        });
        pnlRight_2.add(lblCOG, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 347, -1, -1));

        lblCOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/file_1.png"))); // NOI18N
        lblCOR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblCORFocusGained(evt);
            }
        });
        lblCOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCORMouseClicked(evt);
            }
        });
        pnlRight_2.add(lblCOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 217, -1, -1));

        lblCOGM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/file_1.png"))); // NOI18N
        lblCOGM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblCOGMFocusGained(evt);
            }
        });
        lblCOGM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCOGMMouseClicked(evt);
            }
        });
        pnlRight_2.add(lblCOGM, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 217, -1, -1));

        lblS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/services_2.png"))); // NOI18N
        pnlRight_2.add(lblS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        pnlRight_2.add(lblS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/prev_new.png"))); // NOI18N
        lblPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrevMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPrevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPrevMouseExited(evt);
            }
        });
        pnlRight_2.add(lblPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/new_new.png"))); // NOI18N
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNextMouseExited(evt);
            }
        });
        pnlRight_2.add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, -1, -1));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_2.add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        pnlRight_3.setBackground(new java.awt.Color(249, 234, 208));
        pnlRight_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_3.add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        pnlRight_4.setBackground(new java.awt.Color(197, 186, 165));
        pnlRight_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/prev_new.png"))); // NOI18N
        lblP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblP1MouseExited(evt);
            }
        });
        pnlRight_4.add(lblP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        lblN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/new_new.png"))); // NOI18N
        lblN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblN2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblN2MouseExited(evt);
            }
        });
        pnlRight_4.add(lblN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, -1, -1));

        lblUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/upload_new.png"))); // NOI18N
        lblUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUploadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUploadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUploadMouseExited(evt);
            }
        });
        pnlRight_4.add(lblUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 130));

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlRight_4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 130));

        lblN.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        lblN.setForeground(new java.awt.Color(255, 255, 255));
        pnlRight_4.add(lblN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        pnlP_1.setBackground(new java.awt.Color(197, 186, 165));
        pnlP_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setEditable(false);
        txtUser.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 180, -1));

        lblUser.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Username:");
        pnlP_1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        lblPass.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Password:");
        pnlP_1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 350, -1, -1));

        txtPass.setEditable(false);
        txtPass.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 180, -1));

        lblEditPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/edit.png"))); // NOI18N
        lblEditPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditPassMouseClicked(evt);
            }
        });
        pnlP_1.add(lblEditPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        lblEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/edit.png"))); // NOI18N
        lblEditUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditUserMouseClicked(evt);
            }
        });
        pnlP_1.add(lblEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/mainFrameStudent_1.png"))); // NOI18N
        pnlP_1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblLogo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlP_1.add(lblLogo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        lblB.setForeground(new java.awt.Color(255, 255, 255));
        lblB.setText("Log Out");
        lblB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBMouseClicked(evt);
            }
        });
        pnlP_1.add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User");
        pnlP_1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        pnlRight_4.add(pnlP_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pnlP_2.setBackground(new java.awt.Color(197, 186, 165));
        pnlP_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblBD.setForeground(new java.awt.Color(255, 255, 255));
        lblBD.setText("Birthdate:");
        pnlP_2.add(lblBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 380, -1, -1));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 380, -1));

        txtGL.setEditable(false);
        txtGL.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtGL.setForeground(new java.awt.Color(255, 255, 255));
        txtGL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtGL, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 120, -1));

        lblSection.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblSection.setForeground(new java.awt.Color(255, 255, 255));
        lblSection.setText("Section:");
        pnlP_2.add(lblSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 300, -1, -1));

        txtStrand.setEditable(false);
        txtStrand.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtStrand.setForeground(new java.awt.Color(255, 255, 255));
        txtStrand.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtStrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 170, -1));

        lblLRN.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblLRN.setForeground(new java.awt.Color(255, 255, 255));
        lblLRN.setText("LRN:");
        pnlP_2.add(lblLRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 220, -1, -1));

        txtSY.setEditable(false);
        txtSY.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtSY.setForeground(new java.awt.Color(255, 255, 255));
        txtSY.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtSY, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 130, -1));

        lblSY.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblSY.setForeground(new java.awt.Color(255, 255, 255));
        lblSY.setText("School Year:");
        pnlP_2.add(lblSY, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txtLRN.setEditable(false);
        txtLRN.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtLRN.setForeground(new java.awt.Color(255, 255, 255));
        txtLRN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtLRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 380, -1));

        lblGen.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblGen.setForeground(new java.awt.Color(255, 255, 255));
        lblGen.setText("Birthplace:");
        pnlP_2.add(lblGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 420, -1, -1));

        lblName.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name:");
        pnlP_2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 340, -1, -1));

        txtSection.setEditable(false);
        txtSection.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtSection.setForeground(new java.awt.Color(255, 255, 255));
        txtSection.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 120, -1));

        lblGL.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblGL.setForeground(new java.awt.Color(255, 255, 255));
        lblGL.setText("Grade Level:");
        pnlP_2.add(lblGL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        txtB.setEditable(false);
        txtB.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtB.setForeground(new java.awt.Color(255, 255, 255));
        txtB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 130, -1));

        txtBP.setEditable(false);
        txtBP.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtBP.setForeground(new java.awt.Color(255, 255, 255));
        txtBP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 250, -1));

        lblStrand.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblStrand.setForeground(new java.awt.Color(255, 255, 255));
        lblStrand.setText("Strand:");
        pnlP_2.add(lblStrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 300, -1, -1));

        lblAddress.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Address:");
        pnlP_2.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 460, -1, -1));

        txtA.setEditable(false);
        txtA.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtA.setForeground(new java.awt.Color(255, 255, 255));
        txtA.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 380, -1));

        txtSex.setEditable(false);
        txtSex.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtSex.setForeground(new java.awt.Color(255, 255, 255));
        txtSex.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 70, -1));

        txtR.setEditable(false);
        txtR.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtR.setForeground(new java.awt.Color(255, 255, 255));
        txtR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtR, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 380, 155, -1));

        lblSex.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblSex.setForeground(new java.awt.Color(255, 255, 255));
        lblSex.setText("Sex:");
        pnlP_2.add(lblSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        lblContact.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblContact.setForeground(new java.awt.Color(255, 255, 255));
        lblContact.setText("Contact #:");
        pnlP_2.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 500, -1, -1));

        txtCN.setEditable(false);
        txtCN.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtCN.setForeground(new java.awt.Color(255, 255, 255));
        txtCN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_2.add(txtCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 220, -1));

        lblReligion.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblReligion.setForeground(new java.awt.Color(255, 255, 255));
        lblReligion.setText("Religion:");
        pnlP_2.add(lblReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/mainFrameStudent.png"))); // NOI18N
        pnlP_2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlP_2.add(lblLogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlRight_4.add(pnlP_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pnlP_3.setBackground(new java.awt.Color(197, 186, 165));
        pnlP_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBD1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblBD1.setForeground(new java.awt.Color(255, 255, 255));
        lblBD1.setText("Guardian's Name:");
        pnlP_3.add(lblBD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 380, -1, -1));

        txtMO.setEditable(false);
        txtMO.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtMO.setForeground(new java.awt.Color(255, 255, 255));
        txtMO.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_3.add(txtMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 360, -1));

        txtMN.setEditable(false);
        txtMN.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtMN.setForeground(new java.awt.Color(255, 255, 255));
        txtMN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_3.add(txtMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 360, -1));

        lblLRN1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblLRN1.setForeground(new java.awt.Color(255, 255, 255));
        lblLRN1.setText("Father's Name:");
        pnlP_3.add(lblLRN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 220, -1, -1));

        txtFO.setEditable(false);
        txtFO.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtFO.setForeground(new java.awt.Color(255, 255, 255));
        txtFO.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_3.add(txtFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 360, -1));

        lblSY1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblSY1.setForeground(new java.awt.Color(255, 255, 255));
        lblSY1.setText("Father's Occupation:");
        pnlP_3.add(lblSY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtFN.setEditable(false);
        txtFN.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtFN.setForeground(new java.awt.Color(255, 255, 255));
        txtFN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_3.add(txtFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 360, -1));

        lblGen1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblGen1.setForeground(new java.awt.Color(255, 255, 255));
        lblGen1.setText("Guardian's Occupation:");
        pnlP_3.add(lblGen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 420, -1, -1));

        lblName1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("Mother's Occupation:");
        pnlP_3.add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 340, -1, -1));

        txtGN.setEditable(false);
        txtGN.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtGN.setForeground(new java.awt.Color(255, 255, 255));
        txtGN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_3.add(txtGN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 360, -1));

        txtGO.setEditable(false);
        txtGO.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtGO.setForeground(new java.awt.Color(255, 255, 255));
        txtGO.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_3.add(txtGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 360, -1));

        lblStrand1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblStrand1.setForeground(new java.awt.Color(255, 255, 255));
        lblStrand1.setText("Mother's Name:");
        pnlP_3.add(lblStrand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 300, -1, -1));

        lblAddress1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblAddress1.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress1.setText("Person to Contact:");
        pnlP_3.add(lblAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 460, -1, -1));

        txtPC.setEditable(false);
        txtPC.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtPC.setForeground(new java.awt.Color(255, 255, 255));
        txtPC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_3.add(txtPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 360, -1));

        lblContact1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblContact1.setForeground(new java.awt.Color(255, 255, 255));
        lblContact1.setText("Contact #:");
        pnlP_3.add(lblContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 500, -1, -1));

        txtPCCon.setEditable(false);
        txtPCCon.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtPCCon.setForeground(new java.awt.Color(255, 255, 255));
        txtPCCon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_3.add(txtPCCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 220, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/mainFrameStudent_2.png"))); // NOI18N
        pnlP_3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblLogo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlP_3.add(lblLogo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlRight_4.add(pnlP_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pnlP_4.setBackground(new java.awt.Color(197, 186, 165));
        pnlP_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLRN2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblLRN2.setForeground(new java.awt.Color(255, 255, 255));
        lblLRN2.setText("4Ps Recipient:");
        pnlP_4.add(lblLRN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        btnUI.setBackground(new java.awt.Color(249, 234, 208));
        btnUI.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnUI.setText("Update Information");
        btnUI.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUIActionPerformed(evt);
            }
        });
        pnlP_4.add(btnUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 190, 40));

        txt4Ps.setEditable(false);
        txt4Ps.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txt4Ps.setForeground(new java.awt.Color(255, 255, 255));
        txt4Ps.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_4.add(txt4Ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 360, -1));

        lblSY2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblSY2.setForeground(new java.awt.Color(255, 255, 255));
        lblSY2.setText("Working Student:");
        pnlP_4.add(lblSY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 260, -1, -1));

        txtWorking.setEditable(false);
        txtWorking.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtWorking.setForeground(new java.awt.Color(255, 255, 255));
        txtWorking.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_4.add(txtWorking, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 360, -1));

        lblStrand2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblStrand2.setForeground(new java.awt.Color(255, 255, 255));
        lblStrand2.setText("Nature of Work:");
        pnlP_4.add(lblStrand2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 300, -1, -1));

        txtNature.setEditable(false);
        txtNature.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtNature.setForeground(new java.awt.Color(255, 255, 255));
        txtNature.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_4.add(txtNature, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 360, -1));

        lblName2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblName2.setForeground(new java.awt.Color(255, 255, 255));
        lblName2.setText("Name of Employer:");
        pnlP_4.add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lblBD2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblBD2.setForeground(new java.awt.Color(255, 255, 255));
        lblBD2.setText("Work Address:");
        pnlP_4.add(lblBD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 380, -1, -1));

        txtWorkAd.setEditable(false);
        txtWorkAd.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtWorkAd.setForeground(new java.awt.Color(255, 255, 255));
        txtWorkAd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_4.add(txtWorkAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 360, -1));

        txtNameEmp.setEditable(false);
        txtNameEmp.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtNameEmp.setForeground(new java.awt.Color(255, 255, 255));
        txtNameEmp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlP_4.add(txtNameEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 360, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/mainFrameStudent_2.png"))); // NOI18N
        pnlP_4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblLogo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlP_4.add(lblLogo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlRight_4.add(pnlP_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pnlMain_2.add(pnlRight_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        pnlRight_5.setBackground(new java.awt.Color(249, 234, 208));
        pnlRight_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/prev_new.png"))); // NOI18N
        lblP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPMouseExited(evt);
            }
        });
        pnlRight_5.add(lblP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        lblN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/new_new.png"))); // NOI18N
        lblN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblN1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblN1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblN1MouseExited(evt);
            }
        });
        pnlRight_5.add(lblN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, -1, -1));

        lblC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/contact.png"))); // NOI18N
        pnlRight_5.add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/about.png"))); // NOI18N
        pnlRight_5.add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_5.add(lblLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        getContentPane().add(pnlMain_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 600));

        pnlMain_1.setBackground(new java.awt.Color(36, 56, 50));
        pnlMain_1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                pnlMain_1MouseWheelMoved(evt);
            }
        });
        pnlMain_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/mainFrameB_new.png"))); // NOI18N
        pnlMain_1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/line_2.png"))); // NOI18N
        pnlMain_1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/line_2.png"))); // NOI18N
        pnlMain_1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 435, -1, -1));

        pnlLeft_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_5.setForeground(new java.awt.Color(255, 255, 255));
        lblR_5.setText("ABOUT");
        lblR_5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_5FocusLost(evt);
            }
        });
        lblR_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_5MouseClicked(evt);
            }
        });
        pnlLeft_5.add(lblR_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 180, 40));

        pnlLeft_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_4.setForeground(new java.awt.Color(255, 255, 255));
        lblR_4.setText("PROFILE");
        lblR_4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_4FocusLost(evt);
            }
        });
        lblR_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_4MouseClicked(evt);
            }
        });
        pnlLeft_4.add(lblR_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 180, 40));

        pnlLeft_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_3.setForeground(new java.awt.Color(255, 255, 255));
        lblR_3.setText("STUDENTS");
        lblR_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_3FocusLost(evt);
            }
        });
        lblR_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_3MouseClicked(evt);
            }
        });
        pnlLeft_3.add(lblR_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 40));

        pnlLeft_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_2.setForeground(new java.awt.Color(255, 255, 255));
        lblR_2.setText("SERVICES");
        lblR_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_2FocusLost(evt);
            }
        });
        lblR_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_2MouseClicked(evt);
            }
        });
        pnlLeft_2.add(lblR_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        pnlLeft_1.setBackground(java.awt.Color.gray);
        pnlLeft_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_1.setForeground(new java.awt.Color(255, 255, 255));
        lblR_1.setText("HOME");
        lblR_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_1FocusLost(evt);
            }
        });
        lblR_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_1MouseClicked(evt);
            }
        });
        pnlLeft_1.add(lblR_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        getContentPane().add(pnlMain_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-green.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-red.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void lblR_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_1MouseClicked
        flag = 1;
        lblR_1.requestFocus();
        pnlRight_1.setVisible(true);
        lblN.setText("WELCOME, " + jLabel2.getText().toUpperCase() + "!");
        j = 1;
    }//GEN-LAST:event_lblR_1MouseClicked

    private void lblR_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_2MouseClicked
        flag = 2;
        lblR_2.requestFocus();
        pnlRight_2.setVisible(true);
        j = 2;
    }//GEN-LAST:event_lblR_2MouseClicked

    private void lblR_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_3MouseClicked
        flag = 3;
        lblR_3.requestFocus();
        pnlRight_3.setVisible(true);
        j = 3;
    }//GEN-LAST:event_lblR_3MouseClicked

    private void lblR_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_1FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_1FocusGained

    private void lblR_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_1FocusLost

    }//GEN-LAST:event_lblR_1FocusLost

    private void lblR_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_2FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_2FocusGained

    private void lblR_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_2FocusLost

    }//GEN-LAST:event_lblR_2FocusLost

    private void lblR_3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_3FocusGained
        Changer(flag);

    }//GEN-LAST:event_lblR_3FocusGained

    private void lblR_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_3FocusLost

    }//GEN-LAST:event_lblR_3FocusLost

    private void lblR_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_4MouseClicked
        flag = 4;
        lblR_4.requestFocus();
        pnlRight_4.setVisible(true);
        j = 4;
    }//GEN-LAST:event_lblR_4MouseClicked

    private void lblR_4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_4FocusLost

    }//GEN-LAST:event_lblR_4FocusLost

    private void lblR_4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_4FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_4FocusGained

    private void pnlMain_1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_pnlMain_1MouseWheelMoved
        if (evt.getWheelRotation() == 1) {
            j++;
            if (j >= 6) {
                j = 6;
            }
            System.out.println("up");
            Changer(j);
            FrameSwitch(j);
            System.out.println(j);

        } else if (evt.getWheelRotation() == -1) {
            j--;
            if (j <= 1) {
                j = 1;
            }
            System.out.println("Mouse wheel down");
            Changer(j);
            FrameSwitch(j);
            System.out.println(j);

        }

    }//GEN-LAST:event_pnlMain_1MouseWheelMoved

    private void lblEditUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditUserMouseClicked
        ChangeUsername cu = new ChangeUsername();
        cu.setPassword(password);
        cu.setVisible(true);
        cu.setAlwaysOnTop(true);
        dispose();
    }//GEN-LAST:event_lblEditUserMouseClicked

    private void lblEditPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditPassMouseClicked
        ChangePasswordUser cpu = new ChangePasswordUser();
        cpu.setUsername(txtUser.getText());
        cpu.setPass(password);
        cpu.setUsername(jLabel2.getText());
        cpu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_lblEditPassMouseClicked

    private void lblR_5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_5FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_5FocusGained

    private void lblR_5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblR_5FocusLost

    private void lblR_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_5MouseClicked
        flag = 5;
        lblR_5.requestFocus();
        pnlRight_5.setVisible(true);
        j = 5;
    }//GEN-LAST:event_lblR_5MouseClicked

    private void lblBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBMouseClicked
        LogOut(jLabel2.getText());

    }//GEN-LAST:event_lblBMouseClicked

    private void btnUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUIActionPerformed
        setVisible(false);
        UpdateInfoStudent ui = new UpdateInfoStudent();
        ui.setUsername(jLabel2.getText());
        ui.setVisible(true);
    }//GEN-LAST:event_btnUIActionPerformed

    private void lblUploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUploadMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(130, 130, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblUpload.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(MainFrameStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblUploadMouseClicked

    private void lblUploadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUploadMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblUploadMouseEntered

    private void lblUploadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUploadMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblUploadMouseExited

    private void lblPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrevMouseClicked

    }//GEN-LAST:event_lblPrevMouseClicked

    private void lblPrevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrevMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/prev.png"));
        lblPrev.setIcon(imgIcon);
    }//GEN-LAST:event_lblPrevMouseEntered

    private void lblPrevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrevMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/prev_new.png"));
        lblPrev.setIcon(imgIcon);
    }//GEN-LAST:event_lblPrevMouseExited

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked

    }//GEN-LAST:event_lblNextMouseClicked

    private void lblNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/next.png"));
        lblNext.setIcon(imgIcon);
    }//GEN-LAST:event_lblNextMouseEntered

    private void lblNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/new_new.png"));
        lblNext.setIcon(imgIcon);
    }//GEN-LAST:event_lblNextMouseExited

    private void lblCOGMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOGMMouseClicked
        lblCOGM.requestFocus();
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/file_1.png"));
        lblCOR.setIcon(imgIcon);
        lblCOG.setIcon(imgIcon);
        lblCOUP.setIcon(imgIcon);
        cert = 1;
    }//GEN-LAST:event_lblCOGMMouseClicked

    private void lblCORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCORMouseClicked
        lblCOR.requestFocus();
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/file_1.png"));
        lblCOGM.setIcon(imgIcon);
        lblCOG.setIcon(imgIcon);
        lblCOUP.setIcon(imgIcon);
        cert = 2;
    }//GEN-LAST:event_lblCORMouseClicked

    private void lblCOGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOGMouseClicked
        lblCOG.requestFocus();
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/file_1.png"));
        lblCOR.setIcon(imgIcon);
        lblCOGM.setIcon(imgIcon);
        lblCOUP.setIcon(imgIcon);
        cert = 3;
    }//GEN-LAST:event_lblCOGMouseClicked

    private void lblCOUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOUPMouseClicked
        lblCOUP.requestFocus();
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/file_1.png"));
        lblCOR.setIcon(imgIcon);
        lblCOG.setIcon(imgIcon);
        lblCOGM.setIcon(imgIcon);
        cert = 4;
    }//GEN-LAST:event_lblCOUPMouseClicked

    private void lblCOGMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblCOGMFocusGained
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/file_2.png"));
        lblCOGM.setIcon(imgIcon);
        requestDocument();
    }//GEN-LAST:event_lblCOGMFocusGained

    private void lblCORFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblCORFocusGained
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/file_2.png"));
        lblCOR.setIcon(imgIcon);
        requestDocument();
    }//GEN-LAST:event_lblCORFocusGained

    private void lblCOGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblCOGFocusGained
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/file_2.png"));
        lblCOG.setIcon(imgIcon);
        requestDocument();
    }//GEN-LAST:event_lblCOGFocusGained

    private void lblCOUPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblCOUPFocusGained
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/file_2.png"));
        lblCOUP.setIcon(imgIcon);
        requestDocument();
    }//GEN-LAST:event_lblCOUPFocusGained

    private void lblP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblP1MouseClicked
        if (sw > 0) {
            sw--;
            swish(sw);
        }
    }//GEN-LAST:event_lblP1MouseClicked

    private void lblP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblP1MouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/prev.png"));
        lblP1.setIcon(imgIcon);
    }//GEN-LAST:event_lblP1MouseEntered

    private void lblP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblP1MouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/prev_new.png"));
        lblP1.setIcon(imgIcon);
    }//GEN-LAST:event_lblP1MouseExited

    private void lblN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN2MouseClicked
        
        if (sw < 3) {
            sw+=1;
            swish(sw);
        }
    }//GEN-LAST:event_lblN2MouseClicked

    private void lblN2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN2MouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/next.png"));
        lblN2.setIcon(imgIcon);
    }//GEN-LAST:event_lblN2MouseEntered

    private void lblN2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN2MouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/new_new.png"));
        lblN2.setIcon(imgIcon);
    }//GEN-LAST:event_lblN2MouseExited

    private void lblPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPMouseClicked
        lblC.setVisible(false);
        lblP.setVisible(false);
        lblA.setVisible(true);
        lblN1.setVisible(true);
    }//GEN-LAST:event_lblPMouseClicked

    private void lblPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/prev.png"));
        lblP.setIcon(imgIcon);
    }//GEN-LAST:event_lblPMouseEntered

    private void lblPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/prev_new.png"));
        lblP.setIcon(imgIcon);
    }//GEN-LAST:event_lblPMouseExited

    private void lblN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN1MouseClicked
        lblA.setVisible(false);
        lblN1.setVisible(false);
        lblP.setVisible(true);
        lblC.setVisible(true);
    }//GEN-LAST:event_lblN1MouseClicked

    private void lblN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN1MouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/next.png"));
        lblN1.setIcon(imgIcon);
    }//GEN-LAST:event_lblN1MouseEntered

    private void lblN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN1MouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/new_new.png"));
        lblN1.setIcon(imgIcon);
    }//GEN-LAST:event_lblN1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameStudent().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnUI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblBD;
    private javax.swing.JLabel lblBD1;
    private javax.swing.JLabel lblBD2;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCOG;
    private javax.swing.JLabel lblCOGM;
    private javax.swing.JLabel lblCOR;
    private javax.swing.JLabel lblCOUP;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblContact1;
    private javax.swing.JLabel lblEditPass;
    private javax.swing.JLabel lblEditUser;
    private javax.swing.JLabel lblGL;
    private javax.swing.JLabel lblGen;
    private javax.swing.JLabel lblGen1;
    private javax.swing.JLabel lblHomePage;
    private javax.swing.JLabel lblLRN;
    private javax.swing.JLabel lblLRN1;
    private javax.swing.JLabel lblLRN2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblLogo4;
    private javax.swing.JLabel lblLogo5;
    private javax.swing.JLabel lblLogo6;
    private javax.swing.JLabel lblLogo7;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblN2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPrev;
    private javax.swing.JLabel lblR_1;
    private javax.swing.JLabel lblR_2;
    private javax.swing.JLabel lblR_3;
    private javax.swing.JLabel lblR_4;
    private javax.swing.JLabel lblR_5;
    private javax.swing.JLabel lblReligion;
    private javax.swing.JLabel lblS1;
    private javax.swing.JLabel lblS2;
    private javax.swing.JLabel lblSY;
    private javax.swing.JLabel lblSY1;
    private javax.swing.JLabel lblSY2;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblStrand;
    private javax.swing.JLabel lblStrand1;
    private javax.swing.JLabel lblStrand2;
    private javax.swing.JLabel lblUpload;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlLeft_1;
    private javax.swing.JPanel pnlLeft_2;
    private javax.swing.JPanel pnlLeft_3;
    private javax.swing.JPanel pnlLeft_4;
    private javax.swing.JPanel pnlLeft_5;
    private javax.swing.JPanel pnlMain_1;
    private javax.swing.JPanel pnlMain_2;
    private javax.swing.JPanel pnlP_1;
    private javax.swing.JPanel pnlP_2;
    private javax.swing.JPanel pnlP_3;
    private javax.swing.JPanel pnlP_4;
    private javax.swing.JPanel pnlRight_1;
    private javax.swing.JPanel pnlRight_2;
    private javax.swing.JPanel pnlRight_3;
    private javax.swing.JPanel pnlRight_4;
    private javax.swing.JPanel pnlRight_5;
    private javax.swing.JTextField txt4Ps;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtCN;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtFO;
    private javax.swing.JTextField txtGL;
    private javax.swing.JTextField txtGN;
    private javax.swing.JTextField txtGO;
    private javax.swing.JTextField txtLRN;
    private javax.swing.JTextField txtMN;
    private javax.swing.JTextField txtMO;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameEmp;
    private javax.swing.JTextField txtNature;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtPCCon;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtR;
    private javax.swing.JTextField txtSY;
    private javax.swing.JTextField txtSection;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtStrand;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtWorkAd;
    private javax.swing.JTextField txtWorking;
    // End of variables declaration//GEN-END:variables

    public void sqlconnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql:///dbAccount", "root", "");

        } catch (Exception e) {
            System.out.println("Connection Error: " + e);
        }
    }

    public void saveUsername(String x) {
        username = x;
//wala pa function to nag iisip pako kung ano mas magandang approach
    }

    public void LogOut(String username) {

        String sql = "update infologin set status = ? where username = ?";
        sqlconnect();
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, 0);
            pst.setString(2, username);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Successfully Signed Out");
            audit(username);
            LogIn li = new LogIn();
            li.setVisible(true);
            dispose();
        } catch (Exception e) {
            System.out.println("Error us2: " + e);
        }
    }

    public void Closer() {

        String sql = "update infologin set status = ? where username = ?";
        sqlconnect();
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, 0);
            pst.setString(2, txtUser.getText());
            pst.executeUpdate();
            System.exit(0);
        } catch (Exception e) {
            System.exit(0);
        }
    }

    public void functions() {
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
//        pnlLeft_1.setBackground(c);
        pnlLeft_2.setBackground(c);
        pnlLeft_3.setBackground(c);
        pnlLeft_4.setBackground(c);
        pnlRight_1.setVisible(true);
        pnlRight_2.setVisible(false);
        pnlRight_3.setVisible(false);
        pnlRight_4.setVisible(false);
        txtUser.setText(jLabel2.getText());
        for (int i = 0; i < password.length(); i++) {
            p = p + "•";
        }
        txtPass.setText(p);
        Changer(1);
        pnlP_2.setVisible(false);
        pnlP_3.setVisible(false);
        pnlP_4.setVisible(false);
    }

    public void Changer(int a) {
        switch (a) {
            case 1:
                lblN.setText("WELCOME, " + jLabel2.getText().toUpperCase() + "!");
                pnlLeft_1.setBackground(Color.GRAY);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                pnlLeft_5.setBackground(customColor);
                pnlRight_5.setVisible(false);
                flag = 0;
                break;
            case 2:
                pnlLeft_2.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                pnlLeft_5.setBackground(customColor);
                pnlRight_5.setVisible(false);
                flag = 0;
                break;
            case 3:
                pnlLeft_3.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                pnlLeft_5.setBackground(customColor);
                pnlRight_5.setVisible(false);
                flag = 0;
                break;
            case 4:
                pnlLeft_4.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_5.setBackground(customColor);
                pnlRight_5.setVisible(false);
                flag = 0;
                break;
            case 5:
                pnlLeft_5.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                flag = 0;
                break;
            default:
                break;

        }
    }

    public void FrameSwitch(int j) {
        switch (j) {
            case 1:
                lblR_1.requestFocus();
                pnlRight_1.setVisible(true);
                break;
            case 2:
                lblR_2.requestFocus();
                pnlRight_2.setVisible(true);
                break;
            case 3:
                lblR_3.requestFocus();
                pnlRight_3.setVisible(true);
                break;
            case 4:
                lblR_4.requestFocus();
                pnlRight_4.setVisible(true);
                break;
            case 5:
                lblR_5.requestFocus();
                pnlRight_5.setVisible(true);
                break;
            default:
                break;
        }
    }

    public void getUsername(String x) {
        jLabel2.setText(x);
        functions();
    }

    public void setPassword(String y) {
        password = y;
    }

//    public void setField() {
//        sqlconnect();
//        try {
//            Statement st = con.createStatement();
//            String sql = "select * from infouser";
//            ResultSet rs = st.executeQuery(sql);
//            String sqll = "update infologin set pChange = ? where status = ?";
//            PreparedStatement pst = con.prepareStatement(sqll);
//            pst.setInt(1, 2);
//            pst.setInt(2, 1);
//            pst.executeUpdate();
//
//            while (rs.next()) {
//                if (rs.getString("username").equals(jLabel2.getText())) {
//                    txtLRN.setText(rs.getString("First_Name"));
//                    txtLN.setText(rs.getString("Last_Name"));
//                    txtStrand.setText(rs.getString("Middle_Name"));
//                    txtName.setText(rs.getString("age"));
//                    txtBirthD.setText(rs.getString("birthday"));
//                    txtGen.setText(rs.getString("gender"));
//                }
//            }
//        } catch (Exception e) {
//            System.out.println("Error in changePassword: " + e);
//        }
//    }
    
//    public void setUp() {
//        String sql = "select * from infostudent where LRN = ?";
//        try {
//            PreparedStatement pst = con.prepareStatement(sql);
//            pst.setString(1, username);
//            pst.executeQuery();
//            ResultSet rs = pst.getResultSet();
//            if (rs.first()) {
//                if (!rs.getString("LRN").isEmpty()) {
//                    if (!rs.getString("GradeAndSection").isEmpty()) {
//                        if (!rs.getString("Name").isEmpty()) {
//                            if (!rs.getString("Birthdate").isEmpty()) {
//                                if (!rs.getString("Birthplace").isEmpty()) {
//                                    if (!rs.getString("ContactNumber").isEmpty()) {
//                                        if (!rs.getString("Address").isEmpty()) {
//                                            if (!rs.getString("Religion").isEmpty()) {
//                                                if (!rs.getString("Gender").isEmpty()) {
//                                                    if (!rs.getString("FatherName").isEmpty()) {
//                                                        if (!rs.getString("FatherOccupation").isEmpty()) {
//                                                            if (!rs.getString("MotherName").isEmpty()) {
//                                                                if (!rs.getString("MotherOccupation").isEmpty()) {
//                                                                    if (!rs.getString("GuardianName").isEmpty()) {
//                                                                        if (!rs.getString("GuardianOccupation").isEmpty()) {
//                                                                            if (!rs.getString("PersonToNotif").isEmpty()) {
//                                                                                if (!rs.getString("PersonContact").isEmpty()) {
//                                                                                    if (!rs.getString("4Ps").isEmpty()) {
//                                                                                        if (!rs.getString("WorkingStudent").isEmpty()) {
//                                                                                            if (!rs.getString("NatureOfWork").isEmpty()) {
//                                                                                                if (!rs.getString("EmployerName").isEmpty()) {
//                                                                                                    if (!rs.getString("EnterWorkAddress").isEmpty()) {
//                                                                                                        txtLRN.setText(rs.getString("LRN"));
//                                                                                                        txtName.setText(rs.getString("Name"));
//                                                                                                        txtB.setText(rs.getString("Birthdate"));
//                                                                                                        txtBP.setText(rs.getString("Birthplace"));
//                                                                                                        txtCN.setText(rs.getString("ContactNumber"));
//                                                                                                        txtA.setText(rs.getString("Address"));
//                                                                                                        txtSex.setText(rs.getString("Gender"));
//txtR.setText(rs.getString("Religion"));
//                                                                                                        txtFN.setText(rs.getString("FatherName"));
//                                                                                                        txtFO.setText(rs.getString("FatherOccupation"));
//                                                                                                        txtMN.setText(rs.getString("MotherName"));
//                                                                                                        txtMO.setText(rs.getString("MotherOccupation"));
//                                                                                                        txtGN.setText(rs.getString("GuardianName"));
//                                                                                                        txtGO.setText(rs.getString("GuardianOccupation"));
//                                                                                                        txtPC.setText(rs.getString("PersonToNotif"));
//                                                                                                        txtPCCon.setText(rs.getString("PersonContact"));
//                                                                                                        txt4Ps.setText(rs.getString("4Ps"));
//                                                                                                        if (rs.getInt("WorkingStudent") == 0) {
//                                                                                                            txtWorking.setText("Yes");
//                                                                                                            txtNature.setText(rs.getString("NatureOfWork"));
//                                                                                                            txtNameEmp.setText(rs.getString("EmployerName"));
//                                                                                                            txtWorkAd.setText(rs.getString("EnterWorkAddress"));
//                                                                                                            txtNature.setEnabled(true);
//                                                                                                            txtNameEmp.setEnabled(true);
//                                                                                                            txtWorkAd.setEnabled(true);
//                                                                                                        } else if (rs.getInt("WorkingStudent") == 1) {
//                                                                                                            txtWorking.setText("No");
//             
//                                                                                                            txtNature.setEnabled(true);
//                                                                                                            txtNameEmp.setEnabled(true);
//                                                                                                            txtWorkAd.setEnabled(true);
//                                                                                                        }
//
//                                                                                                    }
//        } catch (Exception e) {
//
//        }
//    }

    final String ALGORITHM = "AES";
    final String KEY = "1Hbfh667adfDEJ78";

    public String decrypt(String value) {

        String decryptedValue = "";
        try {
            Key key = generateKey();
            Cipher cipher = Cipher.getInstance(ALGORITHM);
            cipher.init(Cipher.DECRYPT_MODE, key);
            byte[] decryptedValue64 = new BASE64Decoder().decodeBuffer(value);
            byte[] decryptedByteValue = cipher.doFinal(decryptedValue64);
            decryptedValue = new String(decryptedByteValue, "utf-8");
        } catch (Exception e) {
            System.err.println("Error in Decrypt: " + e);
        }
        return decryptedValue;
    }

    public Key generateKey() throws Exception {
        Key key = new SecretKeySpec(KEY.getBytes(), ALGORITHM);
        return key;
    }

    public void audit(String username) {
        String format = "yyyy-MM-dd hh:mm:s";
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat(format);
        System.out.println(sdf.format(date));
        String sql = "insert into audit values(?,?,?,?)";

        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, sdf.format(date));
            pst.setString(2, username);
            pst.setInt(3, 0);
            pst.setString(4, "User Logged Out");
            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }

    public void requestDocument() {

    }

    public void swish(int a) {
        switch (a) {
            case 0:
                pnlP_1.setVisible(true);
                pnlP_2.setVisible(false);
                pnlP_3.setVisible(false);
                pnlP_4.setVisible(false);
                break;
            case 1:
                pnlP_2.setVisible(true);
                pnlP_1.setVisible(false);
                pnlP_3.setVisible(false);
                pnlP_4.setVisible(false);
                break;
            case 2:
                pnlP_3.setVisible(true);
                pnlP_1.setVisible(false);
                pnlP_2.setVisible(false);
                pnlP_4.setVisible(false);
                break;
            case 3:
                pnlP_4.setVisible(true);
                pnlP_1.setVisible(false);
                pnlP_2.setVisible(false);
                pnlP_3.setVisible(false);
                break;
            default:
                break;

        }
    }

}
