/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Contents;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.FileOutputStream;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;


/**
 *
 * @author kurtt
 */
public class MainFrameAdmin extends javax.swing.JFrame {

    int a = 0;
    int flag = 0;
    int flag2 = 0;
    int f = 2;
    int x = 0;
    int y = -1;
    int z = 0;
    int j = 1;
    int k = 0;
    int[] selected;

    Connection con;
    String username;
    String username2;
    Color c = new Color(0, 0, 0, 1);
    Color customColor = new Color(36, 56, 50);
    SetTable st;
    String user = "";
    String pass = "";
    String order = "Ascending";
    String hoarder = "isAdmin < 3";
    String eggs = "Admin < 3";
    String sqlSearch = "";
    String sqlSearchAudit = "";
    /**
     * Creates new form MainFrame
     */
    public MainFrameAdmin() {
        initComponents();
        functions();
        Methods m = new Methods();
        m.usernames();
        loggingIn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popBlock = new javax.swing.JPopupMenu();
        popDelete = new javax.swing.JPopupMenu();
        delete = new javax.swing.JMenuItem();
        blocks = new javax.swing.JMenuItem();
        pnlMain_2 = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        pnlRight_4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        icSearch = new javax.swing.JLabel();
        scrollP_1 = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        toEnDis2 = new javax.swing.JLabel();
        toDel = new javax.swing.JLabel();
        toDel1 = new javax.swing.JLabel();
        toEnDis1 = new javax.swing.JLabel();
        toDel2 = new javax.swing.JLabel();
        toEnDis = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        toEnDis3 = new javax.swing.JLabel();
        addAccount = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        boxSort = new javax.swing.JComboBox<>();
        boxOrderWhat = new javax.swing.JComboBox<>();
        btnDownload = new javax.swing.JButton();
        pnlRight_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblLogo8 = new javax.swing.JLabel();
        pnlRight_2 = new javax.swing.JPanel();
        lblLogo7 = new javax.swing.JLabel();
        pnlRight_3 = new javax.swing.JPanel();
        lblLogo6 = new javax.swing.JLabel();
        pnlRight_5 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        txtAuditSearch = new javax.swing.JTextField();
        scrollP_2 = new javax.swing.JScrollPane();
        audits = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLogo9 = new javax.swing.JLabel();
        boxSort1 = new javax.swing.JComboBox<>();
        boxOrderWhat1 = new javax.swing.JComboBox<>();
        pnlRight_6 = new javax.swing.JPanel();
        lblLogo2 = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMain_1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlLeft_6 = new javax.swing.JPanel();
        lblR_6 = new javax.swing.JLabel();
        pnlLeft_5 = new javax.swing.JPanel();
        lblR_5 = new javax.swing.JLabel();
        pnlLeft_4 = new javax.swing.JPanel();
        lblR_4 = new javax.swing.JLabel();
        pnlLeft_3 = new javax.swing.JPanel();
        lblR_3 = new javax.swing.JLabel();
        pnlLeft_2 = new javax.swing.JPanel();
        lblR_2 = new javax.swing.JLabel();
        pnlLeft_1 = new javax.swing.JPanel();
        lblR_1 = new javax.swing.JLabel();

        delete.setText("...");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        popDelete.add(delete);

        blocks.setText("...");
        blocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blocksActionPerformed(evt);
            }
        });
        popDelete.add(blocks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain_2.setBackground(new java.awt.Color(249, 234, 208));
        pnlMain_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cross-button-green.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        pnlMain_2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 5, -1, -1));

        pnlRight_4.setBackground(new java.awt.Color(197, 186, 165));
        pnlRight_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        pnlRight_4.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 35, 210, 30));

        icSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/search.png"))); // NOI18N
        pnlRight_4.add(icSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 38, -1, -1));

        scrollP_1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblAccounts.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblAccounts.setSelectionBackground(java.awt.Color.gray);
        tblAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccountsMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblAccountsMouseReleased(evt);
            }
        });
        tblAccounts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblAccountsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblAccountsKeyReleased(evt);
            }
        });
        scrollP_1.setViewportView(tblAccounts);

        pnlRight_4.add(scrollP_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, 560, 440));

        toEnDis2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        toEnDis2.setForeground(new java.awt.Color(255, 255, 255));
        toEnDis2.setText("• ctrl + B");
        pnlRight_4.add(toEnDis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 567, -1, -1));

        toDel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        toDel.setForeground(new java.awt.Color(255, 255, 255));
        toDel.setText("TO DELETE AN ACCOUNT:");
        pnlRight_4.add(toDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 527, -1, -1));

        toDel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        toDel1.setForeground(new java.awt.Color(255, 255, 255));
        toDel1.setText("• right click + delete option");
        pnlRight_4.add(toDel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 547, -1, -1));

        toEnDis1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        toEnDis1.setForeground(new java.awt.Color(255, 255, 255));
        toEnDis1.setText("• right click + enable/disable option");
        pnlRight_4.add(toEnDis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 547, -1, -1));

        toDel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        toDel2.setForeground(new java.awt.Color(255, 255, 255));
        toDel2.setText("• ctrl + D");
        pnlRight_4.add(toDel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 567, -1, -1));

        toEnDis.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        toEnDis.setForeground(new java.awt.Color(255, 255, 255));
        toEnDis.setText("TO ENABLE/DISABLE AN ACCOUNT:");
        pnlRight_4.add(toEnDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 527, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/panelmiddle_3.png"))); // NOI18N
        pnlRight_4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        toEnDis3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        toEnDis3.setForeground(new java.awt.Color(255, 255, 255));
        toEnDis3.setText("TO ADD AN ACCOUNT:");
        pnlRight_4.add(toEnDis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 527, -1, -1));

        addAccount.setBackground(new java.awt.Color(249, 234, 208));
        addAccount.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        addAccount.setText("Add Account");
        addAccount.setBorder(null);
        addAccount.setFocusable(false);
        addAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountActionPerformed(evt);
            }
        });
        pnlRight_4.add(addAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 547, 120, 35));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/panelmiddle_2.png"))); // NOI18N
        pnlRight_4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, -1, -1));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_4.add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        boxSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));
        boxSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSortActionPerformed(evt);
            }
        });
        pnlRight_4.add(boxSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 110, 40));

        boxOrderWhat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Admin", "User" }));
        boxOrderWhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxOrderWhatActionPerformed(evt);
            }
        });
        pnlRight_4.add(boxOrderWhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 90, 40));

        btnDownload.setText("DL");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        pnlRight_4.add(btnDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 60, -1));

        pnlMain_2.add(pnlRight_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        pnlRight_1.setBackground(new java.awt.Color(249, 234, 208));
        pnlRight_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/homePage_2.png"))); // NOI18N
        pnlRight_1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblLogo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_1.add(lblLogo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pnlRight_2.setBackground(new java.awt.Color(197, 186, 165));
        pnlRight_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_2.add(lblLogo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        pnlRight_3.setBackground(new java.awt.Color(249, 234, 208));
        pnlRight_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_3.add(lblLogo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pnlMain_2.add(pnlRight_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        pnlRight_5.setBackground(new java.awt.Color(249, 234, 208));
        pnlRight_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setText("Save File");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlRight_5.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 550, 140, -1));

        txtAuditSearch.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtAuditSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtAuditSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pnlRight_5.add(txtAuditSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 35, 260, 30));

        scrollP_2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        audits.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        audits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        audits.setSelectionBackground(java.awt.Color.gray);
        audits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                auditsMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                auditsMouseReleased(evt);
            }
        });
        audits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                auditsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                auditsKeyReleased(evt);
            }
        });
        scrollP_2.setViewportView(audits);

        pnlRight_5.add(scrollP_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, 560, 440));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/search.png"))); // NOI18N
        pnlRight_5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 38, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/panelmiddle_3.png"))); // NOI18N
        pnlRight_5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        lblLogo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_5.add(lblLogo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 610, 610));

        boxSort1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));
        boxSort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSort1ActionPerformed(evt);
            }
        });
        pnlRight_5.add(boxSort1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 110, 40));

        boxOrderWhat1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Admin", "User" }));
        boxOrderWhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxOrderWhat1ActionPerformed(evt);
            }
        });
        pnlRight_5.add(boxOrderWhat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 110, 40));

        pnlMain_2.add(pnlRight_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        pnlRight_6.setBackground(new java.awt.Color(197, 186, 165));
        pnlRight_6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celo tarangkahan_4.png"))); // NOI18N
        pnlRight_6.add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        lblB.setText("Back");
        lblB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBMouseClicked(evt);
            }
        });
        pnlRight_6.add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        jLabel2.setText("Admin");
        pnlRight_6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        pnlMain_2.add(pnlRight_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        getContentPane().add(pnlMain_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 600));

        pnlMain_1.setBackground(new java.awt.Color(36, 56, 50));
        pnlMain_1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                pnlMain_1MouseWheelMoved(evt);
            }
        });
        pnlMain_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/mainFrameB_new.png"))); // NOI18N
        pnlMain_1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/line_2.png"))); // NOI18N
        pnlMain_1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/line_2.png"))); // NOI18N
        pnlMain_1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 435, -1, -1));

        pnlLeft_6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_6.setForeground(new java.awt.Color(255, 255, 255));
        lblR_6.setText("ABOUT");
        lblR_6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_6FocusLost(evt);
            }
        });
        lblR_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_6MouseClicked(evt);
            }
        });
        pnlLeft_6.add(lblR_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 180, 40));

        pnlLeft_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_5.setForeground(new java.awt.Color(255, 255, 255));
        lblR_5.setText("AUDIT");
        lblR_5.setToolTipText("");
        lblR_5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_5FocusLost(evt);
            }
        });
        lblR_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_5MouseClicked(evt);
            }
        });
        pnlLeft_5.add(lblR_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 180, 40));

        pnlLeft_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_4.setForeground(new java.awt.Color(255, 255, 255));
        lblR_4.setText("ACCOUNTS");
        lblR_4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_4FocusLost(evt);
            }
        });
        lblR_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_4MouseClicked(evt);
            }
        });
        pnlLeft_4.add(lblR_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 40));

        pnlLeft_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_3.setForeground(new java.awt.Color(255, 255, 255));
        lblR_3.setText("CONTACT");
        lblR_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_3FocusLost(evt);
            }
        });
        lblR_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_3MouseClicked(evt);
            }
        });
        pnlLeft_3.add(lblR_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, 40));

        pnlLeft_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_2.setForeground(new java.awt.Color(255, 255, 255));
        lblR_2.setText("SERVICES");
        lblR_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_2FocusLost(evt);
            }
        });
        lblR_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_2MouseClicked(evt);
            }
        });
        pnlLeft_2.add(lblR_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        pnlLeft_1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                pnlLeft_1MouseWheelMoved(evt);
            }
        });
        pnlLeft_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblR_1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblR_1.setForeground(new java.awt.Color(255, 255, 255));
        lblR_1.setText("HOME");
        lblR_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblR_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblR_1FocusLost(evt);
            }
        });
        lblR_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblR_1MouseClicked(evt);
            }
        });
        pnlLeft_1.add(lblR_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        pnlMain_1.add(pnlLeft_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        getContentPane().add(pnlMain_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-green.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-red.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        Closer();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void lblBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBMouseClicked
        LogOut();
    }//GEN-LAST:event_lblBMouseClicked

    private void lblR_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_1MouseClicked
        flag = 1;
        lblR_1.requestFocus();
        pnlRight_1.setVisible(true);
        j = 1;
    }//GEN-LAST:event_lblR_1MouseClicked

    private void lblR_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_2MouseClicked
        flag = 2;
        lblR_2.requestFocus();
        pnlRight_2.setVisible(true);
        j = 2;
    }//GEN-LAST:event_lblR_2MouseClicked

    private void lblR_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_3MouseClicked
        flag = 3;
        lblR_3.requestFocus();
        pnlRight_3.setVisible(true);
        j = 3;
    }//GEN-LAST:event_lblR_3MouseClicked

    private void lblR_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_4MouseClicked
        flag = 4;
        lblR_4.requestFocus();
        pnlRight_4.setVisible(true);
        st = new SetTable(tblAccounts);
        st.addCol();
        st.addRow();
        j = 4;

    }//GEN-LAST:event_lblR_4MouseClicked

    private void lblR_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_1FocusGained
        Changer(flag);

    }//GEN-LAST:event_lblR_1FocusGained

    private void lblR_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_1FocusLost

    }//GEN-LAST:event_lblR_1FocusLost

    private void lblR_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_2FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_2FocusGained

    private void lblR_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_2FocusLost

    }//GEN-LAST:event_lblR_2FocusLost

    private void lblR_3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_3FocusGained
        Changer(flag);

    }//GEN-LAST:event_lblR_3FocusGained

    private void lblR_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_3FocusLost

    }//GEN-LAST:event_lblR_3FocusLost

    private void lblR_4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_4FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_4FocusGained

    private void lblR_4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_4FocusLost

    }//GEN-LAST:event_lblR_4FocusLost

    private void lblR_5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_5FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_5FocusGained

    private void lblR_5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblR_5FocusLost

    private void lblR_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_5MouseClicked
        flag = 5;
        lblR_5.requestFocus();
        pnlRight_5.setVisible(true);
        j = 5;
        SetTable st = new SetTable(audits);
        st.SetTableForAudit(audits);
        st.setTableAudit();
    }//GEN-LAST:event_lblR_5MouseClicked

    private void lblR_6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_6FocusGained
        Changer(flag);
    }//GEN-LAST:event_lblR_6FocusGained

    private void lblR_6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblR_6FocusLost

    }//GEN-LAST:event_lblR_6FocusLost

    private void lblR_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblR_6MouseClicked
        flag = 6;
        lblR_6.requestFocus();
        pnlRight_6.setVisible(true);
        j = 6;
    }//GEN-LAST:event_lblR_6MouseClicked

    private void tblAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountsMouseClicked

        if (tblAccounts.getSelectedRowCount() > 1) {
            selected = new int[tblAccounts.getSelectedRowCount()];
            selected = tblAccounts.getSelectedRows();

            for (int i = 0; i < tblAccounts.getSelectedRowCount(); i++) {
                System.out.print(selected[i] + ", ");
            }
            System.out.println("");
        } else {
            Delete(tblAccounts.getSelectedRow());
            getObject(tblAccounts.getSelectedRow());
        }
//        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
//            evt.consume();
//            updateBlock(flag2, username2);
//            flag2 = 1;
//        }
    }//GEN-LAST:event_tblAccountsMouseClicked

    private void blocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blocksActionPerformed
        updateBlock(flag2, username2);
        flag2 = 1;
    }//GEN-LAST:event_blocksActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (tblAccounts.getSelectedRowCount() > 1) {
            multipleDelete(selected, tblAccounts.getSelectedRowCount());
        } else {
            startDelete(username2);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void tblAccountsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAccountsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_CONTROL && z == 0) {
            z++;
            System.out.println("h1");

        }
        if (evt.getKeyCode() == KeyEvent.VK_D && z == 1) {
            z++;
            System.out.println("h");
        }
        if (z == 2) {

            if (tblAccounts.getSelectedRow() != -1) {
                startDelete(username2);
                String username2 = "";
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please Select An Account To Delete");
            }

            z = 0;
        }
        if (evt.getKeyCode() == KeyEvent.VK_CONTROL && x == 0) {
            x++;

        }
        if (evt.getKeyCode() == KeyEvent.VK_B && x == 1) {
            x++;

        }
        if (x == 2) {

            if (tblAccounts.getValueAt(flag2, 1).equals("ENABLED") || tblAccounts.getValueAt(flag2, 1).equals("DISABLED")) {
                updateBlock(flag2, username2);
                flag2 = 1;
                String username2 = "";
                System.out.println(x);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Select An Account To Block");
            }

            x = 0;
        }
    }//GEN-LAST:event_tblAccountsKeyPressed

    private void tblAccountsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountsMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON3 && tblAccounts.getSelectedRow() != -1) {
            popDelete.show(evt.getComponent(), evt.getX(), evt.getY());
        }
        if (evt.getButton() == MouseEvent.BUTTON3 && tblAccounts.getSelectedRow() != -1 && tblAccounts.getSelectedColumn() == 1) {
            popDelete.show(evt.getComponent(), evt.getX(), evt.getY());
        }


    }//GEN-LAST:event_tblAccountsMouseReleased

    private void tblAccountsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAccountsKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_CONTROL && z > 0) {
            z = 0;

        }
        if (evt.getKeyCode() == KeyEvent.VK_CONTROL && x > 0) {
            x = 0;

        }
    }//GEN-LAST:event_tblAccountsKeyReleased

    private void pnlLeft_1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_pnlLeft_1MouseWheelMoved

    }//GEN-LAST:event_pnlLeft_1MouseWheelMoved

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved

    }//GEN-LAST:event_formMouseWheelMoved

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        String x = txtSearch.getText();
        searchForTheOne(x);
        System.out.println(x);
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void pnlMain_1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_pnlMain_1MouseWheelMoved

        if (evt.getWheelRotation() == 1) {
            j++;
            if (j >= 6) {
                j = 6;
            }
            System.out.println("up");
            Changer(j);
            FrameSwitch(j);
            System.out.println(j);

        } else if (evt.getWheelRotation() == -1) {
            j--;
            if (j <= 1) {
                j = 1;
            }
            System.out.println("Mouse wheel down");
            Changer(j);
            FrameSwitch(j);
            System.out.println(j);

        }
    }//GEN-LAST:event_pnlMain_1MouseWheelMoved

    private void addAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountActionPerformed
        new AddAccount().setVisible(true);
        dispose();
    }//GEN-LAST:event_addAccountActionPerformed

    private void auditsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_auditsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_auditsMouseClicked

    private void auditsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_auditsMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_auditsMouseReleased

    private void auditsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auditsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_auditsKeyPressed

    private void auditsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auditsKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_auditsKeyReleased

    private void boxSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSortActionPerformed
        String s = boxSort.getSelectedItem() + "";
        order = s;
        filter(s);

    }//GEN-LAST:event_boxSortActionPerformed

    private void boxOrderWhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxOrderWhatActionPerformed
        hoarder = boxOrderWhat.getSelectedItem() + "";

        switch (hoarder) {
            case "Admin":
                hoarder = "isAdmin = 1";
                break;
            case "User":
                hoarder = "isAdmin = 0";
                break;
            default:
                hoarder = "isAdmin < 3";
        }
        filter(order);
    }//GEN-LAST:event_boxOrderWhatActionPerformed

    private void boxSort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSort1ActionPerformed
        String s = boxSort1.getSelectedItem() + "";
        order = s;
        filterAudit(order,eggs);
    }//GEN-LAST:event_boxSort1ActionPerformed

    private void boxOrderWhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxOrderWhat1ActionPerformed
        String x = boxOrderWhat1.getSelectedItem() + "";

        switch (x) {
            case "Admin":
                eggs = "Admin = 1";
                break;
            case "User":
                eggs = "Admin = 0";
                break;
            default:
                eggs = "Admin < 3";
        }
        filterAudit(order,eggs);
    }//GEN-LAST:event_boxOrderWhat1ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        print(audits);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        print(tblAccounts);
    }//GEN-LAST:event_btnDownloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameAdmin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAccount;
    private javax.swing.JTable audits;
    private javax.swing.JMenuItem blocks;
    private javax.swing.JComboBox<String> boxOrderWhat;
    private javax.swing.JComboBox<String> boxOrderWhat1;
    private javax.swing.JComboBox<String> boxSort;
    private javax.swing.JComboBox<String> boxSort1;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnSave;
    private javax.swing.JMenuItem delete;
    private javax.swing.JLabel icSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblLogo6;
    private javax.swing.JLabel lblLogo7;
    private javax.swing.JLabel lblLogo8;
    private javax.swing.JLabel lblLogo9;
    private javax.swing.JLabel lblR_1;
    private javax.swing.JLabel lblR_2;
    private javax.swing.JLabel lblR_3;
    private javax.swing.JLabel lblR_4;
    private javax.swing.JLabel lblR_5;
    private javax.swing.JLabel lblR_6;
    private javax.swing.JPanel pnlLeft_1;
    private javax.swing.JPanel pnlLeft_2;
    private javax.swing.JPanel pnlLeft_3;
    private javax.swing.JPanel pnlLeft_4;
    private javax.swing.JPanel pnlLeft_5;
    private javax.swing.JPanel pnlLeft_6;
    private javax.swing.JPanel pnlMain_1;
    private javax.swing.JPanel pnlMain_2;
    private javax.swing.JPanel pnlRight_1;
    private javax.swing.JPanel pnlRight_2;
    private javax.swing.JPanel pnlRight_3;
    private javax.swing.JPanel pnlRight_4;
    private javax.swing.JPanel pnlRight_5;
    private javax.swing.JPanel pnlRight_6;
    private javax.swing.JPopupMenu popBlock;
    private javax.swing.JPopupMenu popDelete;
    private javax.swing.JScrollPane scrollP_1;
    private javax.swing.JScrollPane scrollP_2;
    private javax.swing.JTable tblAccounts;
    private javax.swing.JLabel toDel;
    private javax.swing.JLabel toDel1;
    private javax.swing.JLabel toDel2;
    private javax.swing.JLabel toEnDis;
    private javax.swing.JLabel toEnDis1;
    private javax.swing.JLabel toEnDis2;
    private javax.swing.JLabel toEnDis3;
    private javax.swing.JTextField txtAuditSearch;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public void filter(String s) {
        if (s.equals("Ascending")) {
            String sql = "select * from infologin where " + hoarder + " order by username asc";
            st = new SetTable(tblAccounts);
            st.addCol();
            st.addRowSearch(sql);
        } else {
            String sql2 = "select * from infologin where " + hoarder + " order by username desc";
            st = new SetTable(tblAccounts);
            st.addCol();
            st.addRowSearch(sql2);
        }
    }

    public void filterAudit(String s, String hoard) {
        if (s.equals("Ascending")) {
            String sql = "select * from audit where " + hoard + " order by time asc";
            st = new SetTable(audits);
            st.setTableAuditFiltered(sql);
        } else {
            String sql2 = "select * from audit where " + hoard + " order by time desc";
            st = new SetTable(audits);
            st.setTableAuditFiltered(sql2);
        }
    }
    
    public void sqlconnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql:///dbAccount", "root", "");

        } catch (Exception e) {
            System.out.println("Connection Error: " + e);
        }
    }

    public void saveUsername(String x) {
        username = x;
//wala pa function to nag iisip pako kung ano mas magandang approach
    }

    public void LogOut() {

        String sql = "update infologin set status = ? where status = ?";
        sqlconnect();
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, 0);
            pst.setInt(2, 2);
            pst.executeUpdate();
            if (jLabel2.getText().equals("Admin")) {
                JOptionPane.showMessageDialog(rootPane, "Returning to log in");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Successfully Logged Out");
            }
            LogIn li = new LogIn();
            li.setVisible(true);
            dispose();
        } catch (Exception e) {
            System.out.println("Error us2: " + e);
        }
    }

    public void Closer() {

        String sql = "update infologin set status = ? where status = ?";
        sqlconnect();
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, 0);
            pst.setInt(2, 2);
            pst.executeUpdate();
            System.exit(0);
        } catch (Exception e) {
            System.exit(0);
        }
    }

    public void Changer(int a) {
        switch (a) {
            case 1:
                pnlLeft_1.setBackground(Color.GRAY);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                pnlLeft_5.setBackground(customColor);
                pnlRight_5.setVisible(false);
                pnlLeft_6.setBackground(customColor);
                pnlRight_6.setVisible(false);
                flag = 0;
                break;
            case 2:
                pnlLeft_2.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                pnlLeft_5.setBackground(customColor);
                pnlRight_5.setVisible(false);
                pnlLeft_6.setBackground(customColor);
                pnlRight_6.setVisible(false);
                flag = 0;
                break;
            case 3:
                pnlLeft_3.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                pnlLeft_5.setBackground(customColor);
                pnlRight_5.setVisible(false);
                pnlLeft_6.setBackground(customColor);
                pnlRight_6.setVisible(false);
                flag = 0;
                break;
            case 4:
                pnlLeft_4.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_5.setBackground(customColor);
                pnlRight_5.setVisible(false);
                pnlLeft_6.setBackground(customColor);
                pnlRight_6.setVisible(false);
                flag = 0;
                break;
            case 5:
                pnlLeft_5.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);

                pnlLeft_6.setBackground(customColor);
                pnlRight_6.setVisible(false);
                flag = 0;
                break;
            case 6:
                pnlLeft_6.setBackground(Color.GRAY);
                pnlLeft_1.setBackground(customColor);
                pnlRight_1.setVisible(false);
                pnlLeft_3.setBackground(customColor);
                pnlRight_3.setVisible(false);
                pnlLeft_2.setBackground(customColor);
                pnlRight_2.setVisible(false);
                pnlLeft_4.setBackground(customColor);
                pnlRight_4.setVisible(false);
                pnlLeft_5.setBackground(customColor);
                pnlRight_5.setVisible(false);
                flag = 0;
                break;
//            case 7:
//                pnlLeft_1.setBackground(customColor);
//                pnlRight_1.setVisible(false);
//                pnlLeft_3.setBackground(customColor);
//                pnlRight_3.setVisible(false);
//                pnlLeft_2.setBackground(customColor);
//                pnlRight_2.setVisible(false);
//                pnlLeft_4.setBackground(customColor);
//                pnlRight_4.setVisible(false);
//                pnlLeft_5.setBackground(customColor);
//                pnlRight_5.setVisible(false);
//                pnlLeft_6.setBackground(customColor);
//                pnlRight_6.setVisible(false);
//                break;
//            case 8:
//                pnlLeft_6.setBackground(Color.GRAY);
//                pnlLeft_1.setBackground(customColor);
//                pnlRight_1.setVisible(false);
//                pnlLeft_3.setBackground(customColor);
//                pnlRight_3.setVisible(false);
//                pnlLeft_2.setBackground(customColor);
//                pnlRight_2.setVisible(false);
//                pnlLeft_4.setBackground(customColor);
//                pnlRight_4.setVisible(false);
//                pnlLeft_5.setBackground(customColor);
//                pnlRight_5.setVisible(false);
//                break;
            default:
                break;

        }
    }

    public void FrameSwitch(int j) {
        switch (j) {
            case 1:
                lblR_1.requestFocus();
                pnlRight_1.setVisible(true);
                break;
            case 2:
                lblR_2.requestFocus();
                pnlRight_2.setVisible(true);
                break;
            case 3:
                lblR_3.requestFocus();
                pnlRight_3.setVisible(true);
                break;
            case 4:
                lblR_4.requestFocus();
                pnlRight_4.setVisible(true);
                st = new SetTable(tblAccounts);
                st.addCol();
                st.addRow();
                break;
            case 5:
                lblR_5.requestFocus();
                pnlRight_5.setVisible(true);
                st = new SetTable(audits);
                st.setTableAudit();
                break;
            case 6:
                lblR_6.requestFocus();
                pnlRight_6.setVisible(true);
                break;
            default:
                break;
        }
    }

//    public void adder() {
//        int a = new Methods().checker(txtUser.getText(), pwdPass.getText(), f);
//        if (a == 1) {
//            new Methods().adder(txtUser.getText(), pwdPass.getText(), f);
//            Icon imgIcon = new ImageIcon(getClass().getResource("/icons/user_1.png"));
//            lblUser.setIcon(imgIcon);
//            Icon imgIcon2 = new ImageIcon(getClass().getResource("/icons/admin_1.png"));
//            lblAdmin.setIcon(imgIcon2);
//            txtUser.setText("Enter Username");
//            pwdPass.setText("Enter Password");
//            pass = "";
//            pwdPass.setEchoChar((char) 0);
//            txtUser.setFocusable(false);
//            pwdPass.setFocusable(false);
//            a = 0;
//        } else {
//            Icon imgIcon = new ImageIcon(getClass().getResource("/icons/user_1.png"));
//            lblUser.setIcon(imgIcon);
//            Icon imgIcon2 = new ImageIcon(getClass().getResource("/icons/admin_1.png"));
//            lblAdmin.setIcon(imgIcon2);
//        }
//        f = -1;
//    }
    public void functions() {
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
//        pnlLeft_1.setBackground(c);
        pnlLeft_2.setBackground(c);
        pnlLeft_3.setBackground(c);
        pnlLeft_4.setBackground(c);
        pnlLeft_5.setBackground(c);
        pnlLeft_6.setBackground(c);
        pnlRight_1.setVisible(true);
        pnlRight_2.setVisible(false);
        pnlRight_3.setVisible(false);
        pnlRight_4.setVisible(false);
        pnlRight_5.setVisible(false);
        pnlRight_6.setVisible(false);
        Changer(1);
//        txtUser.setBackground(new java.awt.Color(0, 0, 0, 1));
//        pwdPass.setBackground(new java.awt.Color(0, 0, 0, 1));
//        lblAdmin.setFocusable(false);
//        lblUser.setFocusable(false);
//        txtUser.setFocusable(false);
//        pwdPass.setFocusable(false);
//        pnlSort.setVisible(false);
//        pnlSort.setBackground(new java.awt.Color(249, 234, 208, 100));
        txtSearch.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtAuditSearch.setBackground(new java.awt.Color(0, 0, 0, 1));
        tblAccounts.setDefaultEditor(Object.class, null);
        new SetTable().fixTable(scrollP_1);
        new SetTable().fixTable(scrollP_2);

    }

//    public void check(int c) {
//        if (c == 1) {
//            if (a == 0) {
//                a = 1;
//                Icon imgIcon = new ImageIcon(getClass().getResource("/icons/admin_2.png"));
//                lblAdmin.setIcon(imgIcon);
//                f = 1;
//                System.out.println(f);
//            } else if (a == 1) {
//                Icon imgIcon = new ImageIcon(getClass().getResource("/icons/admin_1.png"));
//                lblAdmin.setIcon(imgIcon);
//                a = 0;
//                f = -1;
//            }
//        } else if (c == 0) {
//            if (a == 0) {
//                a = 1;
//                Icon imgIcon = new ImageIcon(getClass().getResource("/icons/user_2.png"));
//                lblUser.setIcon(imgIcon);
//                f = 0;
//                System.out.println(f);
//            } else if (a == 1) {
//                Icon imgIcon = new ImageIcon(getClass().getResource("/icons/user_1.png"));
//                lblUser.setIcon(imgIcon);
//                a = 0;
//                f = -1;
//            }
//        }
//    }
    public void getObject(int row) {
        if (tblAccounts.getValueAt(row, 1).equals("ENABLED")) {
            blocks.setText("DISABLE");
            flag2 = 3;
            username2 = tblAccounts.getValueAt(row, 0) + "";
            System.out.println(username2);
        } else if (tblAccounts.getValueAt(row, 1).equals("DISABLED")) {
            blocks.setText("ENABLE");
            flag2 = 0;
            username2 = tblAccounts.getValueAt(row, 0) + "";
        }
    }

    public void updateBlock(int x, String username) {
        sqlconnect();

        int i = JOptionPane.showConfirmDialog(rootPane, "Do You Want To Block " + username + "'s Account?");

        if (i == 0) {
            switch (x) {
                case 0:
                    try {
                    String sql = "update infologin set block = ? where username = ?";
                    PreparedStatement pst;
                    pst = con.prepareStatement(sql);
                    pst.setInt(1, 0);
                    pst.setString(2, username);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, username + "'s Account Has Been Unblocked");
                    audit(jLabel2.getText(), username, 3);
                } catch (Exception e) {
                    System.out.println("Error in updateBlock case 0: " + e);
                }
                break;
                case 3:
                    try {
                    String sql = "update infologin set block = ? where username = ?";
                    PreparedStatement pst;
                    pst = con.prepareStatement(sql);
                    pst.setInt(1, 3);
                    pst.setString(2, username);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, username + "'s Account Has Been Blocked");
                    audit(jLabel2.getText(), username, 2);
                } catch (Exception e) {
                    System.out.println("Error in updateBlock case 3: " + e);
                }
                break;
            }
            st = new SetTable(tblAccounts);
            st.addCol();
            st.addRow();
            txtSearch.setText("");
        }
    }

    public void Delete(int row) {
        delete.setText("Delete Account");
        username2 = tblAccounts.getValueAt(row, 0) + "";
    }

    public void startDelete(String username) {
        sqlconnect();
        try {
            Statement st = con.createStatement();
            String sql2 = "select * from infologin where username = '" + username + "'";
            ResultSet rs = st.executeQuery(sql2);

            while (rs.next()) {
                if (rs.getInt("status") == 0) {
                    int i = JOptionPane.showConfirmDialog(rootPane, "Do You Want To Delete " + username + "'s Account?");

                    if (i == 0) {
                        try {
                            String sql = "DELETE FROM infologin WHERE username = ?;";
                            PreparedStatement pst;
                            pst = con.prepareStatement(sql);
                            pst.setString(1, username);
                            pst.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, username + "'s Account Has Been Deleted");
                            audit(jLabel2.getText(), username, 1);

                        } catch (Exception e) {
                            System.out.println("Error in updateBlock case 0: " + e);
                        }

                        SetTable sts = new SetTable(tblAccounts);
                        sts.addCol();
                        sts.addRow();
                        txtSearch.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, username + "'s Account Can't Be Deleted \n \nREASON: The Account Is Logged In");
                    break;
                }
            }
        } catch (Exception e) {
        }

    }

    public void searchForTheOne(String search) {
        String sql;

        if (!search.equals(null)) {
            if (search.trim().equalsIgnoreCase("!admin")) {
                sql = "select * from infologin where isAdmin = 1";
            } else if (search.trim().equalsIgnoreCase("!user")) {
                sql = "select * from infologin where isAdmin = 0";
            } else {
                sql = "select * from infologin where username like '%" + search + "%'";
            }

            st = new SetTable(tblAccounts);
            st.addCol();
            st.addRowSearch(sql);
        }
    }

    public void multipleDelete(int[] selected, int row) {

        int i = JOptionPane.showConfirmDialog(rootPane, "Do You Want To Delete The Selected Accounts?");
        if (i == 0) {
            for (int x = 0; x < row; x++) {
                sqlconnect();

                try {
                    String sql = "DELETE FROM infologin WHERE username = ?;";
                    PreparedStatement pst;
                    pst = con.prepareStatement(sql);
                    pst.setString(1, tblAccounts.getValueAt(selected[i], 0) + " ");
                    pst.executeUpdate();

                } catch (Exception e) {
                    System.out.println("Error in updateBlock case 0: " + e);
                }

                st = new SetTable(tblAccounts);
                st.addCol();
                st.addRow();
                txtSearch.setText("");
            }
            JOptionPane.showMessageDialog(rootPane, "Selected Account Has Been Deleted");
        }
        selected = new int[0];
    }

    public void loggingIn() {
        sqlconnect();
        String sql = "select * from infologin where status = 2 and isAdmin = 1";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                jLabel2.setText(rs.getString("username"));
                lblB.setText("LogOut");
            }

        } catch (Exception e) {
            System.out.println("Error in loggingIn: " + e);
        }

    }

    public void audit(String adminname, String username, int x) {
        String format = "yyyy-MM-dd hh:mm:ss";
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat(format);
        System.out.println(sdf.format(date));
        String sql = "insert into audit values(?,?,?)";

        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, sdf.format(date));
            if (username.equals("Admin")) {
                pst.setString(2, "Power User");
            } else {
                pst.setString(2, adminname);
            }
            switch (x) {
                case 1:
                    pst.setString(3, "Deleted " + username + "'s Account");
                    break;
                case 2:
                    pst.setString(3, "Blocked " + username + "'s Account");
                    break;
                case 3:
                    pst.setString(3, "Unblocked " + username + "'s Account");
                    break;
            }
            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
    
    private void print(JTable Tbl) {
        try {
            Tbl.print();
        } catch (Exception e) {
        }
    }
}
