/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Contents;
//Kung Babaguhin Yung Design Pabago Nalang Ahahahaha

import com.mysql.jdbc.Connection;
import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kurtt
 */
public class UpdateInfo extends javax.swing.JFrame {

    int flag;
    Connection con;
    String firstName = "", lastName = "", middleName = "", age = "", birthday = "", gender = "";
    String username = "";
    String password = "";
    int f = 0;
    int day = 0, month = 0, year = 0;
    Date date = new Date();
    LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    int yearC = localDate.getYear();
    int monthC = localDate.getMonthValue();
    int dayC = localDate.getDayOfMonth();
    int ageU = 0;

    /**
     * Creates new form MainFrame
     */
    public UpdateInfo() {
        initComponents();
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        txtFN.setFocusable(false);
        txtLN.setFocusable(false);
        txtMN.setFocusable(false);
        txtA.setFocusable(false);
        txtB.setFocusable(false);
        txtFN.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtLN.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtMN.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtA.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtB.setBackground(new java.awt.Color(0, 0, 0, 1));
        sqlconnect();
        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                day = date.getDay();
                month = date.getMonth();
                year = date.getYear();
                System.out.println(year);
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
                ageU = yearC - year;
                if (month > monthC || (month == monthC && day > dayC)) {
                    ageU = ageU - 1;
                }
                txtA.setText(ageU + "");
            }
        });
        rbtnG.add(rbtnMale);
        rbtnG.add(rbtnFemale);
        rbtnG.add(rbtnOthers);
        jLabel2.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnG = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnUI = new javax.swing.JButton();
        txtB = new javax.swing.JTextField();
        txtA = new javax.swing.JTextField();
        txtMN = new javax.swing.JTextField();
        txtLN = new javax.swing.JTextField();
        txtFN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbtnMale = new radio_button.RadioButtonCustom();
        rbtnFemale = new radio_button.RadioButtonCustom();
        rbtnOthers = new radio_button.RadioButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 56, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cPassTop_new.png"))); // NOI18N
        jPanel3.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/cross-button.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        jPanel3.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 0, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 110));

        jPanel2.setBackground(new java.awt.Color(249, 234, 208));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUI.setBackground(new java.awt.Color(249, 234, 208));
        btnUI.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnUI.setForeground(new java.awt.Color(36, 56, 60));
        btnUI.setText("Update Information");
        btnUI.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUI.setFocusable(false);
        btnUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUIActionPerformed(evt);
            }
        });
        jPanel2.add(btnUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 190, 40));

        txtB.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtB.setForeground(java.awt.Color.gray);
        txtB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtB.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBCaretUpdate(evt);
            }
        });
        txtB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBFocusLost(evt);
            }
        });
        txtB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBMouseClicked(evt);
            }
        });
        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });
        txtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBKeyPressed(evt);
            }
        });
        jPanel2.add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 220, -1));

        txtA.setEditable(false);
        txtA.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtA.setForeground(java.awt.Color.gray);
        txtA.setText("Age");
        txtA.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtA.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtACaretUpdate(evt);
            }
        });
        txtA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAFocusLost(evt);
            }
        });
        txtA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAMouseClicked(evt);
            }
        });
        txtA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAKeyPressed(evt);
            }
        });
        jPanel2.add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, -1));

        txtMN.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtMN.setForeground(java.awt.Color.gray);
        txtMN.setText("Enter Middle Name");
        txtMN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtMN.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtMNCaretUpdate(evt);
            }
        });
        txtMN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMNFocusLost(evt);
            }
        });
        txtMN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMNMouseClicked(evt);
            }
        });
        txtMN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMNKeyPressed(evt);
            }
        });
        jPanel2.add(txtMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, 310, -1));

        txtLN.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtLN.setForeground(java.awt.Color.gray);
        txtLN.setText("Enter Last Name");
        txtLN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtLN.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtLNCaretUpdate(evt);
            }
        });
        txtLN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLNFocusLost(evt);
            }
        });
        txtLN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLNMouseClicked(evt);
            }
        });
        txtLN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLNKeyPressed(evt);
            }
        });
        jPanel2.add(txtLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 310, -1));

        txtFN.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtFN.setForeground(java.awt.Color.gray);
        txtFN.setText("Enter First Name");
        txtFN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtFN.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtFNCaretUpdate(evt);
            }
        });
        txtFN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFNFocusLost(evt);
            }
        });
        txtFN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFNMouseClicked(evt);
            }
        });
        txtFN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFNKeyPressed(evt);
            }
        });
        jPanel2.add(txtFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, 310, -1));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 248, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/bottompart_3.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, -1, -1));

        rbtnMale.setBackground(new java.awt.Color(36, 56, 50));
        rbtnMale.setForeground(java.awt.Color.gray);
        rbtnMale.setText("Male");
        rbtnMale.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rbtnMale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnMaleItemStateChanged(evt);
            }
        });
        jPanel2.add(rbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 175, -1, -1));

        rbtnFemale.setBackground(new java.awt.Color(36, 56, 50));
        rbtnFemale.setForeground(java.awt.Color.gray);
        rbtnFemale.setText("Female");
        rbtnFemale.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rbtnFemale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnFemaleItemStateChanged(evt);
            }
        });
        jPanel2.add(rbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 175, -1, -1));

        rbtnOthers.setBackground(new java.awt.Color(36, 56, 50));
        rbtnOthers.setForeground(java.awt.Color.gray);
        rbtnOthers.setText("Others");
        rbtnOthers.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rbtnOthers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnOthersItemStateChanged(evt);
            }
        });
        jPanel2.add(rbtnOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 175, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 370, 290));

        setSize(new java.awt.Dimension(370, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon imgIcon = new ImageIcon(getClass().getResource("/icons/cross-button-red.png"));
        btnClose.setIcon(imgIcon);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUIActionPerformed
        UpdateInformation();
    }//GEN-LAST:event_btnUIActionPerformed

    private void txtFNCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtFNCaretUpdate
        firstName = txtFN.getText();
    }//GEN-LAST:event_txtFNCaretUpdate

    private void txtFNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFNFocusGained
        Color customColor = new Color(249, 234, 208);
        if(txtFN.getText().equals("Enter First Name")){
        txtFN.setText("");
        }else{
        txtFN.setText(firstName);
        }
        txtFN.setForeground(customColor);
    }//GEN-LAST:event_txtFNFocusGained

    private void txtFNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFNFocusLost
        txtFN.setForeground(Color.GRAY);
        if (firstName.trim().length() != 0 && !firstName.equals("Enter First Name")) {// may trim dito kanina
            txtFN.setText(firstName);
        } else {
            txtFN.setText("Enter First Name");
            firstName = "";
        }
    }//GEN-LAST:event_txtFNFocusLost

    private void txtFNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNKeyPressed

    private void txtFNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFNMouseClicked
        txtFN.setFocusable(true);
        txtLN.setFocusable(true);
        txtMN.setFocusable(true);
        txtA.setFocusable(true);
        txtB.setFocusable(true);
        txtFN.requestFocus();
    }//GEN-LAST:event_txtFNMouseClicked

    private void txtLNCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtLNCaretUpdate
        lastName = txtLN.getText();
    }//GEN-LAST:event_txtLNCaretUpdate

    private void txtLNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLNFocusGained
        Color customColor = new Color(249, 234, 208);
        if(txtLN.getText().equals("Enter Last Name")){
        txtLN.setText("");
        }else{
        txtLN.setText(lastName);
        }
        txtLN.setForeground(customColor);
    }//GEN-LAST:event_txtLNFocusGained

    private void txtLNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLNFocusLost
        txtLN.setForeground(Color.GRAY);
        if (lastName.trim().length() != 0 && !lastName.equals("Enter Last Name")) {// may trim dito kanina
            txtLN.setText(lastName);
        } else {
            txtLN.setText("Enter Last Name");
            lastName = "";
        }
    }//GEN-LAST:event_txtLNFocusLost

    private void txtLNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLNMouseClicked
        txtFN.setFocusable(true);
        txtLN.setFocusable(true);
        txtMN.setFocusable(true);
        txtA.setFocusable(true);
        txtB.setFocusable(true);
        txtLN.requestFocus();
    }//GEN-LAST:event_txtLNMouseClicked

    private void txtLNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNKeyPressed

    private void txtMNCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMNCaretUpdate
        middleName = txtMN.getText();
    }//GEN-LAST:event_txtMNCaretUpdate

    private void txtMNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMNFocusGained
        Color customColor = new Color(249, 234, 208);
        if(txtMN.getText().equals("Enter Middle Name")){
        txtMN.setText("");
        }else{
        txtMN.setText(middleName);
        }
        txtMN.setForeground(customColor);
    }//GEN-LAST:event_txtMNFocusGained

    private void txtMNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMNFocusLost
        txtMN.setForeground(Color.GRAY);
        if (middleName.trim().length() != 0 && !middleName.equals("Enter Middle Name")) {// may trim dito kanina
            txtMN.setText(middleName);
        } else {
            txtMN.setText("Enter Middle Name");
            middleName = "";
        }
    }//GEN-LAST:event_txtMNFocusLost

    private void txtMNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMNMouseClicked
        txtFN.setFocusable(true);
        txtLN.setFocusable(true);
        txtMN.setFocusable(true);
        txtA.setFocusable(true);
        txtB.setFocusable(true);
        txtMN.requestFocus();
    }//GEN-LAST:event_txtMNMouseClicked

    private void txtMNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMNKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMNKeyPressed

    private void txtACaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtACaretUpdate
        age = txtA.getText();
    }//GEN-LAST:event_txtACaretUpdate

    private void txtAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAFocusGained

    private void txtAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAFocusLost

    private void txtAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAMouseClicked

    private void txtAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAKeyPressed

    private void txtBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBKeyPressed

    private void txtBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBMouseClicked
        txtB.requestFocus();
        txtFN.setFocusable(true);
        txtLN.setFocusable(true);
        txtMN.setFocusable(true);
        txtA.setFocusable(true);
        txtB.setFocusable(true);

    }//GEN-LAST:event_txtBMouseClicked

    private void txtBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBFocusLost

    }//GEN-LAST:event_txtBFocusLost

    private void txtBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBFocusGained

    }//GEN-LAST:event_txtBFocusGained

    private void txtBCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBCaretUpdate

    }//GEN-LAST:event_txtBCaretUpdate

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        dateChooser.showPopup();


    }//GEN-LAST:event_txtBActionPerformed

    private void rbtnMaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnMaleItemStateChanged
        Color customColor = new Color(249, 234, 208);
        if (f == 0) {
            rbtnMale.setForeground(customColor);
            f = 1;
        } else {
            rbtnMale.setForeground(Color.gray);
            f = 0;
        }
        gender = "Male";
    }//GEN-LAST:event_rbtnMaleItemStateChanged

    private void rbtnFemaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnFemaleItemStateChanged
        Color customColor = new Color(249, 234, 208);
        if (f == 0) {
            rbtnFemale.setForeground(customColor);
            f = 1;
        } else {
            rbtnFemale.setForeground(Color.gray);
            f = 0;
        }
        gender = "Female";
    }//GEN-LAST:event_rbtnFemaleItemStateChanged

    private void rbtnOthersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnOthersItemStateChanged
        Color customColor = new Color(249, 234, 208);
        if (f == 0) {
            rbtnOthers.setForeground(customColor);
            f = 1;
        } else {
            rbtnOthers.setForeground(Color.gray);
            f = 0;
        }
        gender = "Others";
    }//GEN-LAST:event_rbtnOthersItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnUI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLogo;
    private radio_button.RadioButtonCustom rbtnFemale;
    private javax.swing.ButtonGroup rbtnG;
    private radio_button.RadioButtonCustom rbtnMale;
    private radio_button.RadioButtonCustom rbtnOthers;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtMN;
    // End of variables declaration//GEN-END:variables

    public void sqlconnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql:///dbAccount", "root", "");

        } catch (Exception e) {
            System.out.println("Connection Error: " + e);
        }
    }

    public void UpdateInformation() { //dito aayusin
        try {

            String sql = "update infouser set First_Name = ?, Last_Name = ?, Middle_Name = ?, age = ?, birthday = ?, gender = ? where username = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtFN.getText());
            pst.setString(2, txtLN.getText());
            pst.setString(3, txtMN.getText());
            pst.setInt(4, ageU);
            pst.setString(5, txtB.getText());
            pst.setString(6, gender);
            pst.setString(7, jLabel2.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Personal Information Updated!");
            audit(jLabel2.getText(), 0);
            MainFrameStudent mfu = new MainFrameStudent();
            mfu.setPassword(password);
            mfu.getUsername(jLabel2.getText());
            mfu.setVisible(true);
            dispose();

        } catch (Exception e) {
            System.out.println("Error in UpdateStatus1: " + e);
        }
    }

    public void UpdateStatus1() {// dito rin

        try {

            String sql = "update infologin set pChange = ? where username = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, 1);
            pst.setString(2, jLabel2.getText());
            pst.executeUpdate();
//            JOptionPane.showMessageDialog(rootPane, "Password Changed!");
//            MainFrameUser mfu = new MainFrameUser();
//            mfu.setVisible(true);
//            dispose();

        } catch (Exception e) {
            System.out.println("Error in UpdateStatus1: " + e);
        }
    }

    public void UpdateInfo1() {
        int c = check();
        if (c == 1) {
            try {
                Statement st = con.createStatement();
                String sql = "select * from infologin";
                ResultSet rs = st.executeQuery(sql);

                while (rs.next()) {
                    if (rs.getString("username").equals(jLabel2.getText())) {
                        if (rs.getInt("pChange") == 1) {
                            UpdateStatus1();
                            UpdateInformation();
                            break;
                        }
                    } else {
                        System.err.println(rs.getInt("status"));
                    }

                }
            } catch (Exception e) {
                System.out.println("Error in changePassword: " + e);
            }
        }
    }
//

    public int check() {
        String fn = txtFN.getText();
        String ln = txtLN.getText();
        String mn = txtMN.getText();
        int c = 0;
        if (fn.trim().length() != 0 && !fn.equals("Enter First Name")) {

            if (ln.trim().length() != 0 && !ln.equals("Enter Last Name")) {
                if (mn.trim().length() != 0 && !mn.equals("Enter Middle Name")) {
                    if (gender.equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "Please select a gender!");
                    } else {
                        c = 1;
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Middle Name must not be blank!");
                    fn = "";
                    ln = "";
                    mn = "";
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Last Name must not be blank!");
                fn = "";
                ln = "";
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "First name must not be blank!");
            fn = "";
        }
//        if (pwdCP.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "New password should not be blank");
//        } else if (pwdCCP.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Confirm new password should not be blank");
//        } else if (!pwdCP.getText().equals(pwdCCP.getText())) {
//            JOptionPane.showMessageDialog(null, "New password and confirm new password should be the same");
//        } else {
//            c = 1;
//        }
        return c;
    }

    public void showPassword1() {
//        System.out.println(flag);
//        if (flag == 0) {
////                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/1667188461554126440-128.png"));
////                lblEye.setIcon(ImgIcon);
//            pwdCP.setEchoChar((char) 0);
////            lblS_1.setText("HIDE");
//            lblH_1.setVisible(true);
//            flag = 1;
//        }
//        else if (flag == 1) {
//
//            pwdCP.setEchoChar('\u25cf');
//            lblS_1.setVisible(true);
////            lblS_1.setb
//            flag = 0;
//        }
    }

    public void showPassword2() {
//        if (flag == 0) {
////                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/1667188461554126440-128.png"));
////                lblEye.setIcon(ImgIcon);
//            pwdCCP.setEchoChar((char) 0);
//            lblH_2.setVisible(true);
//            flag = 1;
//        }
//        else if (flag == 1) {
////                Icon ImgIcon = new ImageIcon(getClass().getResource("/Image/19318253741554126440-128.png"));
////                lblEye.setIcon(ImgIcon);
//            pwdCCP.setEchoChar('\u25cf');
//            lblS_2.setText("SHOW");
//            flag = 0;
//        }
    }

    public void hidePassword1() {
//        pwdCP.setEchoChar('\u25cf');
//        lblS_1.setVisible(true);
//        lblH_1.setVisible(false);
////            lblS_1.setb
//        flag = 0;
    }

    public void hidePassword2() {
//        pwdCCP.setEchoChar('\u25cf');
//        lblS_2.setVisible(true);
//        lblH_2.setVisible(false);
//        flag = 0;
    }

     public void setUsername(String x) {
        username = x;
        getUsername(x);
    }
    public String getUsername(String x) {
        return x;
    }

    public void setPassword(String y) {
        password = y;
        System.out.println(password);
    }

    public void setInfo(String user, String p, String fn, String ln, String mn, String a, String b, String g) {
        txtFN.setText(fn);
        txtLN.setText(ln);
        txtMN.setText(mn);
        txtA.setText(a);
        txtB.setText(b);
        password = p;
        if (g.equals("Male")) {
            rbtnMale.setSelected(true);
        } else if (g.equals("Female")) {
            rbtnFemale.setSelected(true);
        }
        jLabel2.setText(user);
        System.out.println(user);
    }

    public void audit(String username, int i) {
        String format = "yyyy-MM-dd hh:mm:ss";
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat(format);
        System.out.println(sdf.format(date));
        String sql = "insert into audit values(?,?,?,?)";

        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, sdf.format(date));
            pst.setString(2, username);
            pst.setInt(3, i);
            pst.setString(4, "Updated Information");
            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
}
